-- The Wire — daily transaction wire schema.
-- Sprint 12. Disjoint from reporting.py and team_pages/.
-- Idempotent. CREATE IF NOT EXISTS only.
--
-- Design rationale:
--  * One row per Wire entry. Every entry is an "action that happened" plus
--    the editorial caption ("why it matters") rendered alongside it.
--  * `actor_kind` keeps the table polymorphic — a coordinator hire, a
--    portal commit, a CFP-committee statement, and a conference-realignment
--    rumor all live here. The "WHO did this" cell on the rendered page is
--    derived from `program_display` + `actor_kind`.
--  * `why_it_matters` is the editorial column. Generated by Sonnet,
--    voice-validated by the gate in team_pages/voice_validator.py before
--    insertion. We store the *validated* string only; if validation fails
--    twice the row keeps the action but `why_it_matters` falls back to a
--    short factual restatement (the renderer treats both identically).
--  * `impact_label` + `impact_color` are denormalised display values — we
--    score impact at generation time so the renderer is dumb. Color names
--    are CSS-class hints ("amber", "muted", "green", "red"); the actual
--    color values live in the renderer/template, not the data layer, so a
--    palette swap doesn't require a migration.
--  * `historical_comp` is optional — only ~25% of entries get one (the
--    pattern-recognition column from the Communal Engagement Strategy).
--  * `related_thread_slug` is the seam to Storyline Threads (Sprint 10).
--    NULL for entries that don't connect to an active Thread.
--  * `fan_intel_velocity_spike` carries the cohort-velocity reading from
--    the existing fan-intel pipeline — it's the input that lets the
--    Reaction Story sprint (separate) decide whether this Wire entry is
--    loud enough to spawn a Reaction Story. Stored as INTEGER 0-100.
--  * Indexes: most reads are "last N entries" (homepage, Wire index) or
--    "last N entries for program X" (team page integrations).

CREATE TABLE IF NOT EXISTS wire_entries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    occurred_at DATETIME NOT NULL,
    program_slug TEXT,
    program_display TEXT NOT NULL,
    actor_kind TEXT NOT NULL CHECK(actor_kind IN ('program','player','coach','conference','committee')),
    action TEXT NOT NULL,
    why_it_matters TEXT NOT NULL,
    impact_label TEXT NOT NULL,
    impact_color TEXT NOT NULL,
    historical_comp TEXT,
    source_kind TEXT NOT NULL,
    source_url TEXT,
    source_name TEXT,
    related_thread_slug TEXT,
    fan_intel_velocity_spike INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_wire_occurred ON wire_entries(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_wire_program ON wire_entries(program_slug, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_wire_actor_kind ON wire_entries(actor_kind, occurred_at DESC);

-- Stable de-dup key: same program + same action + same day = same entry.
-- Used by the ingestion path's upsert to avoid re-inserting the same
-- transaction across daily runs.
CREATE UNIQUE INDEX IF NOT EXISTS idx_wire_dedupe
    ON wire_entries(program_slug, action, date(occurred_at));
