-- Player Narrative Arc LLM cache — Wave 15.
--
-- Three-act season story (opening / pivot / finish) generated by
-- local Ollama. One row per (player_id, season_year). content_hash
-- lets the generator detect when game-log inputs changed and
-- regenerate idempotently.

CREATE TABLE IF NOT EXISTS player_narrative_arc (
    player_id     INTEGER NOT NULL,
    season_year   INTEGER NOT NULL,
    content_hash  TEXT    NOT NULL,
    opening_text  TEXT    NOT NULL,
    pivot_text    TEXT    NOT NULL,
    finish_text   TEXT    NOT NULL,
    model_id      TEXT,
    generated_at  TEXT    NOT NULL,
    PRIMARY KEY (player_id, season_year)
);

CREATE INDEX IF NOT EXISTS idx_player_narrative_arc_season
    ON player_narrative_arc(season_year);
