"""Banned-phrase + register validator for Edition editorial content.

Local copy for Sprint 9. The Sprint 8 ``team_pages.voice_validator`` is the
canonical implementation; this is a deliberately-narrow subset that covers
the banned-phrase list from ``docs/CHRONICLE_EDITORIAL_BRIEF.md`` Rule 6,
plus the additional restrictions for the Edition voice register from
``docs/EDITORIAL_POSITIONING_AND_CONTENT_TYPES.md``.

When the two diverge, this file is authoritative for editorial content
generated by the editions module — Sprint 8's validator runs against
team-page Chronicle cards.
"""
from __future__ import annotations

import re
from dataclasses import dataclass


# Phrases that must never appear (case-insensitive). Sourced from the
# Chronicle brief Rule 6 + Edition voice register guardrails.
BANNED_PHRASES: tuple[str, ...] = (
    "stat engine",
    "our algorithm",
    "our pipeline",
    "the pipeline",
    "tier 1",
    "tier 2",
    "summary stat",
    "compression of outcome",
    "a flattening of",
    "every season produces one of these",
    "this table",
    "this card",
    "this module",
    "this widget",
    "the methodology",
    "the scoring",
    "the engine",
    # Edition-specific: avoid the AI/system-tells.
    "as an ai",
    "as a language model",
    "i was trained",
    "let me know if",
    "feel free to",
    # Generic-magazine clichés that signal voice failure.
    "stay tuned",
    "without further ado",
)

# Words that as the *subject* of a sentence indicate meta-commentary.
SUBJECT_BANNED_AT_START: tuple[str, ...] = (
    "the pattern is",
    "the data shows",
    "the numbers show",
    "the stats show",
)


@dataclass
class ValidationResult:
    ok: bool
    violations: list[str]

    def __bool__(self) -> bool:
        return self.ok


def validate(text: str) -> ValidationResult:
    """Check ``text`` against banned phrases. Returns a result with a
    sorted, deduped list of violation strings."""
    if not text:
        return ValidationResult(ok=True, violations=[])
    lowered = text.lower()
    hits: set[str] = set()
    for phrase in BANNED_PHRASES:
        if phrase in lowered:
            hits.add(phrase)
    # Subject-banned at start of any sentence.
    sentences = re.split(r"(?<=[.!?])\s+", lowered)
    for sentence in sentences:
        s = sentence.strip()
        for prefix in SUBJECT_BANNED_AT_START:
            if s.startswith(prefix):
                hits.add(prefix)
    return ValidationResult(ok=not hits, violations=sorted(hits))


def assert_valid(text: str, label: str = "text") -> None:
    """Raise ``ValueError`` if ``text`` contains banned phrases."""
    result = validate(text)
    if not result.ok:
        raise ValueError(
            f"voice_validator: {label} contains banned phrases: "
            f"{', '.join(result.violations)}"
        )
