"""The Big Ten Reasserting — chapter seeds (Big Ten conference voice register)."""
THREAD_SLUG = "big-ten-reasserting"

CHAPTERS = [
    {
        "chapter_number": 1,
        "title": "January 8: Michigan Wins, and the Conference Stops Apologizing",
        "dek": "The Wolverines beat Washington for the title. Harbaugh was already half out the door. The Big Ten had a trophy for the first time since 2014, and the conference's posture toward the SEC argument changed within 48 hours.",
        "body_markdown": """The Big Ten won a national championship on the night of January 8, 2024. Michigan beat Washington 34-13 in Houston in a game that Jim Harbaugh — already, by widely-reported accounts, in the final stages of negotiating his return to the NFL — coached with the visible satisfaction of a man who had finally gotten the trophy he had spent his entire career insisting was the only one that mattered. The win was the Big Ten's first national title since Ohio State's 2014 run under Urban Meyer. It was Michigan's first since 1997. It ended a fifteen-year stretch during which the SEC had functionally claimed the trophy as its own product.

What the title did to the Big Ten's institutional posture was visible inside the week. The conference had spent fifteen years arguing — sometimes credibly, sometimes performatively — that its football was as good as the SEC's, that the perception gap was a media construction, that the recruiting maps were closing. The arguments had been correct about some things and wrong about others. What the arguments had been missing was the thing only a trophy can supply: the structural permission to stop arguing. Michigan's win supplied it. Adam Rittenberg at ESPN, in his first column the morning after the title game, wrote: *"The Big Ten woke up Tuesday in a different posture toward the rest of the sport. The argument the conference has been having since 2009 has not been won — one trophy does not erase fifteen years — but the argument has been retired in its previous form. The conference now has the option to argue from a different position. Whether it takes the option is the next question."*

The conference, in the form of commissioner Tony Petitti, took the option immediately. Petitti's first public remarks the morning after the title game were notable for what they did not contain. They did not contain the defensive posture of his predecessor Kevin Warren. They did not contain comparative claims about strength of schedule. They did not contain the careful tone that Big Ten commissioners had used for fifteen years to manage the gap between the conference's self-image and its trophy case. They contained, instead, a single sentence that Pete Sampson at The Athletic flagged as the institutional inflection point: *"This is what the work has been for."* No comparison. No qualification. No defense. The work has been for this. The work has now produced this.

What the work had been for, in the institutional sense, was the systemic catch-up that the conference had been doing for the better part of a decade. The recruiting investment. The facility arms race that Harbaugh, Day, Franklin, and Tucker had pushed their schools through in the late 2010s. The NIL infrastructure that the Big Ten had been slower to build than the SEC but had built nonetheless. The expansion to USC and UCLA that summer of 2022 (and to Washington and Oregon in summer 2023, which we will track in earnest in [Chapter 2](#chapter-2)) — all of that work had been pointed at the trophy. The trophy had landed. The next question was what the conference did with the trophy.

The answer, internally, was the answer the boards had been waiting for. On 11Warriors — the Ohio State board that has the institutional memory of the conference's frustration as deeply as anyone — a thread by user TressBall titled *"What Michigan winning means for us"* ran 1,400 replies in the first week and the dominant view was an unusual one. The Buckeye partisans were, broadly, not unhappy that Michigan had won. They were unhappy that *Ohio State* had not won. The framing distinction is small and important. The thread's most-cited reply: *"Michigan winning means the conference has its trophy. The Big Ten is not the SEC's understudy anymore. We hate Michigan. We do not hate the conference's posture changing. The next trophy is ours to take."*

The Penn State boards, on Black Shoe Diaries, ran a parallel thread that was more measured but landed in the same place. *"We have spent twenty years watching Penn State be the best of the conference's almost-good-enoughs,"* one reply read. *"That role no longer exists in the conference's self-image. The conference's self-image is now: we win national championships. The pressure on Penn State to actually win one — instead of being the best almost-good-enough — has just gone up. That is fine. That is what we wanted."*

The recruiting implications were the second-order story that everyone in the conference understood would matter most. Bruce Feldman wrote it up in The Athletic on January 11: *"The Big Ten has spent fifteen years making the case to recruits in the SEC footprint that they could win at the highest level by going north. The case has been credible. The case has been incomplete. The trophy completes the case. The next two recruiting cycles are going to test whether the recruits and their families absorb the new evidence. They will. The recruiting maps will keep closing."* The early data has supported Feldman's read. The 2024 cycle's December early signing period, which closed about four weeks before the title game and was therefore not affected by it, saw the SEC sign a class average about 0.18 points higher per recruit than the Big Ten on the major-services scale. The 2025 cycle's December signing period, which closed roughly twelve months after the trophy landed, saw the gap close to 0.06. That is not the kind of gap closure that flips the recruiting balance overnight. It is the kind that, sustained, restructures the talent inflows of the sport over half a decade.

The Harbaugh exit, which we are not relitigating in this chapter because the exit is its own story that several Detroit beat writers have already documented, did not undermine the title. The trophy stays in Ann Arbor. Sherrone Moore, the offensive coordinator promoted to head coach almost immediately after Harbaugh's NFL move was finalized, inherits a roster that won and a culture that, broadly, the Michigan boards trust him to preserve. *"We trust Sherrone,"* one MGoBlog thread by user TheVictorVictorius read. *"We trust him because he was in the building when the trophy was won. He was not the architect of it. He was a load-bearing wall. The architect's house is now his house. Whether he keeps the house standing is the next chapter."*

That next chapter — what the conference does with the trophy, and what its second consecutive year looks like as a structurally elevated league — is the one we will track. The conference is not quite finished asserting itself. The work continues. The trophy is now the floor, not the ceiling. We pick this up in Chapter 2 with the expansion absorbing USC, UCLA, Washington, and Oregon and what that does to the conference's competitive ceiling.""",
        "byline": "From The Big Ten Reasserting Department",
        "published_at": "2024-01-12 10:00:00",
        "read_time_minutes": 7,
        "referenced_chapter_ids": [],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Adam Rittenberg", "label": "ESPN column", "url": None, "date": "2024-01-09"},
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic (Petitti remarks)", "url": None, "date": "2024-01-09"},
            {"kind": "beat-writer", "name": "Bruce Feldman", "label": "The Athletic recruiting analysis", "url": None, "date": "2024-01-11"},
            {"kind": "board", "name": "TressBall", "label": "11Warriors thread", "url": None, "date": "2024-01-10"},
            {"kind": "board", "name": "TheVictorVictorius", "label": "MGoBlog thread", "url": None, "date": "2024-01-25"},
        ],
        "pull_quote": "This is what the work has been for.",
    },
    {
        "chapter_number": 2,
        "title": "August: The Coast-to-Coast Conference, and the Roster That Won the Argument",
        "dek": "The Big Ten now spans four time zones and 18 schools. Ohio State's roster reads like a championship blueprint. The argument with the SEC isn't over. The argument's terms have changed.",
        "body_markdown": """We picked this up in [Chapter 1](#chapter-1) by noting that Michigan's title gave the conference structural permission to stop arguing from a defensive position. Eight months later, the conference is in the position of arguing from a different one entirely: it is the conference with the most-watched team in football (Ohio State, returning a championship-caliber roster), the most expensive television contract in college sports (the new media deal that fully kicks in this season), and the geographic reach (USC, UCLA, Washington, Oregon now full members) that no other conference can match. The new argument the conference is having is not "are we as good as the SEC?" It is "is the conference's coast-to-coast structure the model the rest of college football will be forced to adopt?"

The geographic-reach question is the one that has produced the most visible operational friction. The schedule, as Pete Sampson worked through in The Athletic on August 12, has had to accommodate eighteen teams across four time zones. The travel realities for USC, UCLA, Washington, and Oregon are not trivial. USC played four East Coast road games last season. UCLA had a four-game stretch in October that included travel of more than 6,000 air miles. The boards in Westwood and Eugene have been polite about the travel and direct about the games. *"We knew what we signed up for,"* a thread on BoardOfProspects (Oregon) by user DucksDeep ran in late August. *"We signed up to play national football. National football includes travel. The travel is the cost. The cost was always the deal."*

What the conference did not have to apologize for, this fall, was the on-field product. Ohio State's roster was the most-discussed roster in football coming into the season for reasons that withstood scrutiny. Will Howard had transferred in from Kansas State to play quarterback. Jeremiah Smith was the most-anticipated true freshman wide receiver in a generation. Emeka Egbuka was returning. Jack Sawyer and JT Tuimoloau were back on the defensive front. Ryan Day's roster construction — built partly through high-school recruiting (the conference's traditional strength), partly through portal acquisitions (a more recent capability the program has scaled into) — read, as Adam Rittenberg wrote in his August preview, *"like the roster a championship-caliber program builds when the championship-caliber program has all the resources it needs and the institutional discipline to deploy them at the right positions."*

The Cover 3 podcast (ep 296, October 2024) framed the same point in a register that fit the moment. *"Ohio State has been building toward this kind of roster for ten years,"* Andy Staples said. *"What they have this year is what they have been trying to have. The conference around them — Michigan, Penn State, Oregon, Washington, USC, even the lower half — is, on average, structurally better than the conference around them was five years ago. The conference around them is what the trophy from January was building toward. The conference now matches the trophy."*

The conference matching the trophy is the line that landed best, in the boards' summer reception. A 11Warriors thread by user TressBall titled *"The conference is good now"* ran 600 replies in mid-August and the dominant note was a kind of careful Buckeye satisfaction. *"For most of my conference-watching life,"* one reply read, *"the Big Ten was Ohio State, Michigan, Penn State on a good day, Wisconsin on a good day, Iowa on a good day, and a long tail of programs that Ohio State beat 56-0. That conference is gone. The new conference has Oregon. It has USC. It has Washington when it's good. It has Penn State which is good more years now. It has Iowa which is annoyingly good. The conference is good now. That is a different thing than the SEC's depth, but it is also not the conference of 2009 anymore."*

What the conference does not yet have, structurally, is the thing the SEC still has and the SEC has had since the late 2000s: the recruiting depth in its native footprint that lets the conference replenish itself without depending on national-cycle wins. The Big Ten's recruiting footprint is wider than ever — USC, UCLA, Oregon, and Washington bring California and Pacific Northwest pipelines that the conference has never had before — but the per-state production in the conference's traditional Midwest footprint is not what the SEC's per-state production in its Southeast footprint is. The Bruce Feldman recruiting column we cited in [Chapter 1](#chapter-1) made this point and it remains true: the conference's structural advantage is its institutional resources and its expanded geographic reach, not its native recruiting density. The conference can match the SEC at the top of cycles. Whether the conference can match the SEC across cycles, year after year, is the question that the next three or four cycles will answer.

The early-season evidence has been encouraging. Penn State, which we noted in [Chapter 1](#chapter-1) had been consigned to "best almost-good-enough" status, is having a season that may finally produce the thing the program has been working toward — Drew Allar at QB, an OL that has cohered, a defense that is the best in the conference. James Franklin's seat will not be hot if the season ends 11-1; if the season ends with a CFP semifinal appearance, Franklin will sign an extension. Oregon, in its first conference season, started 5-0 and did not look out of place at the top of the standings. USC, conversely, has been the chapter the conference's Eastern teams have written off — a 3-3 start, a defense that has not held up against the conference's better offenses, a Lincoln Riley who, the boards on Trojan Football Forum have noted, is *"finding out that the SEC offense schematically translates poorly to the Big Ten when your defense isn't physical enough to keep the games in scoreboard ranges where the offense matters."*

The chapter Ohio State will write — and the chapter we will track in [Chapter 3](#chapter-3) — is the back half of this season. The roster is the roster. The conference is the conference. The trophy from last year is in Ann Arbor. The next trophy is, depending on which board you read, either Ohio State's to lose or Penn State's to take.""",
        "byline": "From The Big Ten Reasserting Department",
        "published_at": "2024-10-15 09:30:00",
        "read_time_minutes": 7,
        "referenced_chapter_ids": [1],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic schedule analysis", "url": None, "date": "2024-08-12"},
            {"kind": "beat-writer", "name": "Adam Rittenberg", "label": "ESPN August preview", "url": None, "date": "2024-08-22"},
            {"kind": "podcast", "name": "Cover 3", "label": "Episode 296 (Andy Staples)", "url": None, "date": "2024-10-21"},
            {"kind": "board", "name": "TressBall", "label": "11Warriors thread", "url": None, "date": "2024-08-18"},
            {"kind": "board", "name": "DucksDeep", "label": "BoardOfProspects (Oregon)", "url": None, "date": "2024-08-28"},
        ],
        "pull_quote": "The conference now matches the trophy.",
    },
    {
        "chapter_number": 3,
        "title": "January: Ohio State Wins, and the Conference Has Two in a Row",
        "dek": "Will Howard, Jeremiah Smith, and Day's redemption arc. Back-to-back Big Ten national titles. The conference is no longer arguing. It is holding the trophy.",
        "body_markdown": """Ohio State won the College Football Playoff on a Monday night in Atlanta on January 20, beating Notre Dame 34-23 in a title game that Will Howard played the cleanest 60-minute quarterback game of his career and Jeremiah Smith — a true freshman whom Ryan Day will not coach again because the freshman is going pro after one season, which is the kind of thing the modern game does — caught the touchdown pass that effectively ended the game in the third quarter. The trophy was the Big Ten's second in a row. We picked this thread up in [Chapter 1](#chapter-1) by noting Michigan's title gave the conference structural permission to stop arguing. We picked it up in [Chapter 2](#chapter-2) by noting Ohio State's roster looked like the kind of roster the conference's expansion was supposed to make possible. The roster delivered. The trophy stayed in the Big Ten.

What back-to-back means, structurally, is the chapter the boards spent the week after the title game working through. The SEC had won the trophy nine times in the eleven seasons of the College Football Playoff before 2024. The Big Ten won the next two. That is the kind of run that resets the league-superiority conversation that we noted in [Chapter 1](#chapter-1) was waiting on the trophy to be retired in its previous form. *"The argument is over,"* Adam Rittenberg wrote in his ESPN postgame column. *"It was over after Michigan in the procedural sense. It is over after Ohio State in the structural sense. The Big Ten is the league that won the first two cycles of the new bracket. That is the line. The next argument the conferences have will be about the third trophy. The previous argument is not coming back."*

The Day redemption arc is the personal-narrative chapter that Ohio State fans had been waiting for since the 2022-2023 stretch when Day's seat was the hottest seat in the conference. We do not need to relitigate the seat-temperature history; the boards have done it at length and the chronology is well-documented. What's worth noting is that Day's win against Notre Dame was specifically a win against the program that, in the 2022 Fiesta Bowl, had given Day his second of the four most-discussed losses of his Ohio State tenure. The redemption was not subtle. Day, in his on-field interview with ESPN's Holly Rowe immediately after the trophy presentation, was characteristically terse: *"This is what we built. This is who built it. We are not done."* The line read as both relief and as institutional reassertion — Day acknowledging that the work had landed and serving notice that the work would continue. The boards on 11Warriors received the line with the kind of restored confidence the program had been short of for two years. *"Day is our coach,"* one TressBall reply read. *"He has always been our coach. There were two years where we were not sure whether the program would survive his coaching. Those years are over. The program survived. The program is winning national titles. Day is our coach."*

Penn State's familiar near-miss arrived on schedule in the semifinals, which we should note because the program's narrative is part of the conference's narrative. The Nittany Lions, with Drew Allar finally healthy and an OL that had cohered, beat Boise State in the first round, beat SMU in the quarterfinal, and lost 27-13 to Notre Dame in the Cotton Bowl semifinal. The loss was the program's third CFP-era close-call defeat to a top-three opponent. James Franklin signed an extension in February. The fanbase, on Black Shoe Diaries, processed the close-call with the institutional resignation that has become familiar. *"We were closer than we have been,"* one reply read. *"We were not close enough. The program is in the conversation. The program has not closed the conversation. The pattern from [Chapter 2](#chapter-2) — that Penn State has been the conference's best almost-good-enough — has not been broken. We will see if the next cycle breaks it. We are tired of waiting for the next cycle to break it."*

The conference's depth, which we noted in [Chapter 2](#chapter-2) was the structural question the next several cycles would answer, has held up at the top in '24 in ways that warrant noting. Oregon went 13-1 in its first conference season, lost only to Ohio State in the Big Ten Championship Game, and earned a top-four seed and a CFP bye. Indiana, of all programs, went 11-2 under Curt Cignetti's second-year overperformance and made the bracket as a 9-seed, which was the most-discussed at-large bid of the cycle. Iowa went 8-4. Michigan went 8-5 under Sherrone Moore (the price of replacing Harbaugh and losing meaningful talent to the NFL). Penn State, as noted, made the semifinal. The conference's top six teams were, by S&P+ and most other composite metrics, the strongest top-six grouping of any conference. The bottom of the conference was the bottom of the conference; that has not changed. But the top six is now structurally consistent with the top six of the SEC.

The Solid Verbal pod, in their post-title-game episode (ep 542, January 22), made the most-careful version of the conference-superiority argument that the moment permits. *"Two trophies in two years is not a fifteen-year run,"* Ty Hildenbrandt said. *"The SEC's claim was a fifteen-year claim. The Big Ten has not made a fifteen-year claim yet. What the Big Ten has done is interrupt the SEC's fifteen-year claim with two years of trophies and a structural elevation that the conference has been working toward for a decade. That is not the same as having claimed the throne. It is, factually, the conference holding the trophy. We can say that without overclaiming. We can also notice that the SEC is, at the moment, in the position the Big Ten was in for fifteen years — the conference with the case to make, the conference whose argument is ahead of its trophies."*

That framing is the framing we will carry forward. The conference is not the SEC. The conference is no longer the SEC's understudy. The trophy from January is the trophy. The next chapter — Chapter 4 — picks up in the spring of 2026, two cycles in, when we have a clearer view of whether the back-to-back was the start of a run or the peak of one.""",
        "byline": "From The Big Ten Reasserting Department",
        "published_at": "2025-01-23 11:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Adam Rittenberg", "label": "ESPN postgame column", "url": None, "date": "2025-01-21"},
            {"kind": "tv-radio", "name": "Holly Rowe", "label": "ESPN trophy-presentation interview (Day)", "url": None, "date": "2025-01-20"},
            {"kind": "podcast", "name": "Solid Verbal", "label": "Episode 542 (Hildenbrandt)", "url": None, "date": "2025-01-22"},
            {"kind": "board", "name": "TressBall", "label": "11Warriors postgame thread", "url": None, "date": "2025-01-21"},
        ],
        "pull_quote": "Two trophies in two years is not a fifteen-year run. But it is the conference, factually, holding the trophy.",
    },
    {
        "chapter_number": 4,
        "title": "Spring 2026: Three's the Question, and the Sherrone Moore Year",
        "dek": "Two cycles after Michigan's title, the conference is structurally elevated and now confronting the chapter every elevated conference eventually confronts: the third trophy is the proof.",
        "body_markdown": """The spring of 2026 finds the Big Ten in the position the SEC was in around 2008 — a conference with two consecutive national titles, a roster of contenders that is now broader than at any point in its modern history, and the structural question of whether the elevation will produce a run or peak as a back-to-back. The third trophy is the proof. We picked this up in [Chapter 1](#chapter-1) by noting that one trophy gave the conference permission to stop arguing from a defensive position; in [Chapter 2](#chapter-2) by tracking the expansion absorption that gave the conference its widest geographic footprint in history; in [Chapter 3](#chapter-3) by noting that back-to-back was structurally different from one trophy. The third would be different again.

The 2025 season did not produce the third. Texas won the College Football Playoff. Texas is in the SEC. The argument that two trophies for the Big Ten was the start of a run has been complicated by the fact that the conference did not win the third in the immediate next opportunity. The argument that two trophies was a peak has been complicated by the fact that the conference's losses in 2025 were close, structural-quality losses (Ohio State lost in the CFP semifinal to Texas in a game that was tied at the half) rather than the kind of blowout exits that signal a conference's competitive ceiling. The truth is between the two arguments. The conference is structurally elevated. The conference is also not yet a run. The third trophy is what it always was: the marker.

The Sherrone Moore year — Michigan's second under Moore, which finished 9-4 with a Citrus Bowl appearance and a 2025 season that saw the program continue to rebuild from the personnel losses that followed the title — is the chapter we should look at hardest. Moore inherited the trophy from Harbaugh, as we noted in [Chapter 1](#chapter-1). His first year (8-5) was the price of replacement and roster turnover. His second year was the proof-of-concept year. The proof of concept was incomplete. Michigan beat Penn State, beat USC, lost to Ohio State (predictably) and to Iowa (less predictably) and to Oregon (in the conference's most-watched game of the season). The Citrus Bowl, against an SEC opponent (Tennessee), Michigan won. The bowl win does not produce a championship. The bowl win does produce evidence that the program is now functioning, on its own terms, under a coach who is not the coach who built the trophy.

Pete Sampson at The Athletic wrote the most-careful evaluation of Moore's second year on January 4. *"Sherrone Moore has done what the program needed him to do in the immediate post-Harbaugh period,"* Sampson wrote. *"He has not done it at championship pace. He has done it at the pace of a coach building a program after a once-in-a-generation title cycle ended with the head coach leaving for the NFL. The work is incremental. The work is real. The trophy from January 2024 will not be repeated by Sherrone Moore in his first three years; the program is not built that way under his leadership. The program may produce another trophy in his fifth or sixth year. The program will not produce one in his second."* That is the most-honest read available. The MGoBlog boards have, broadly, accepted it. The TheVictorVictorius reply we cited in [Chapter 1](#chapter-1) about whether the architect's house is now Moore's house has aged into a chapter of its own. The house is Moore's. The house is standing. The house is not, currently, producing trophies. The house is producing 9-4 seasons that are 9-4 because the conference around Michigan is structurally better than the conference Michigan won the trophy in.

What the structurally-better-conference around Michigan looks like — and what the boards are processing in the spring — is the cleanest evidence that [Chapter 2](#chapter-2)'s "the conference now matches the trophy" framing has held. Ohio State was 11-2 in 2025 and made the CFP semifinal. Penn State was 11-2 and made the bracket as a 4-seed; Drew Allar's senior year delivered exactly what the program had been waiting for, and the program lost in the CFP quarterfinal in a way that, in 2008, would have been described as predictable disappointment and now reads as evidence-of-real-elevation that the program has not converted. Oregon went 12-1 in its second conference season and won the Big Ten Championship Game, beating Ohio State in a game that defenders of the conference's elevation will quote for a decade. USC under Lincoln Riley went 9-4, played a defense that Riley re-staffed for the 2025 season, and finally looked like a program that might compete for a Big Ten title in 2026 or 2027. Indiana, after Curt Cignetti's overperforming '24 season, regressed to 8-5 — predictable, Cignetti has been promoted to the SEC vacancy at Auburn (which we will track in the carousel thread), and the Hoosiers are now searching for a successor who can sustain the elevation Cignetti built.

The recruiting evidence has continued to bend toward the conference's structural reassertion. The 2026 cycle's December early signing period — which is the cycle that reflects 24 months of trophy-driven recruiting work — saw the Big Ten close the per-recruit gap to within 0.04 of the SEC, the smallest gap in the modern era of the major-services scale. Ohio State signed the No. 1 class. Penn State signed the No. 5 class. Oregon signed the No. 8 class. The conference's top three classes were better, on average, than the SEC's top three. The next three were not. The structural reassertion is real at the top. The depth comparison continues.

The Solid Verbal pod's spring update (ep 612, March 18) made the framing that we think will hold for the next chapter. *"The Big Ten is the conference of the moment,"* Mark Rogers said. *"The Big Ten is also a conference whose 'moment' has now lasted two cycles and is asking whether it can last five. Two cycles is a feature. Five is a fixture. The conference is in year three of asking whether it can be a fixture. The answer to that question is the next several years' worth of trophies. The 2026 season is the next data point."*

We pick this up after the 2026 season's verdict lands. The chapter to come is the one where Day, Moore, Lanning at Oregon, Franklin at Penn State, and Riley at USC all arrive at the same stretch of November having had the off-season to prove what the conference is. The conference, two cycles in, is what we said it was: structurally elevated, not yet a fixture, holding the trophies it has and asking whether it can hold the next one.""",
        "byline": "From The Big Ten Reasserting Department",
        "published_at": "2026-04-23 09:45:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2, 3],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic Moore-year evaluation", "url": None, "date": "2026-01-04"},
            {"kind": "podcast", "name": "Solid Verbal", "label": "Episode 612 (Mark Rogers)", "url": None, "date": "2026-03-18"},
            {"kind": "board", "name": "TheVictorVictorius", "label": "MGoBlog continued thread", "url": None, "date": "2026-02-19"},
            {"kind": "beat-writer", "name": "Adam Rittenberg", "label": "ESPN spring conference outlook", "url": None, "date": "2026-04-08"},
        ],
        "pull_quote": "Two cycles is a feature. Five is a fixture. The conference is in year three of asking whether it can be a fixture.",
    },
]
