"""Coaching Carousel · 2026-27 — chapter seeds (Editor's Desk + trade-pub register)."""
THREAD_SLUG = "coaching-carousel-2026-27"

CHAPTERS = [
    {
        "chapter_number": 1,
        "title": "November 5: The Pre-Firing-Season Hot Board",
        "dek": "Nine sitting head coaches are within one bad month of an exit conversation. Three of those conversations are already happening. Buyout structures, AD postures, and the names being whispered in agent offices.",
        "body_markdown": """The pre-firing-season Hot Board for the 2026 cycle, as of November 5, 2025, has more meaningful heat on it than any cycle since the 2021 Lincoln-Riley-and-Brian-Kelly week that reshaped half of college football's coaching map in 96 hours. The structural conditions are similar: a Power Four ecosystem in which the gap between the SEC/Big Ten and everyone else has widened, a CFP expansion that has elevated the cost of underperformance for any program with structural playoff aspirations, and an AD class that — across roughly six of the most-watched programs in the country — has the institutional permission to make a change if the season's last month produces the kind of evidence that justifies one.

We are starting this thread now because the next eight weeks are going to produce the chapters this thread is built around. The work of tracking a coaching carousel is the work of recording, in something close to real time, what the names being whispered are, what the structural conditions of the openings are, and what the eventual hires actually mean. We are doing it with the trade-publication discipline Bruce Feldman, Pete Thamel, and Brett McMurphy have spent the past decade modeling. We are doing it with the discourse-synthesis layer that the boards and the podcast circuit produce around each name. The chapters are what they are. We will write them as they land.

The Hot Board, as Brett McMurphy had it on Action Network on November 4, has nine seats with measurable heat:

**Hugh Freeze, Auburn.** Year three. 6-3 with three games remaining (Texas A&M, Mercer, Alabama). The board has been hot since the loss at Vanderbilt in early October, which Auburn fans have spent six weeks processing in a register that is recognizably distinct even by Auburn standards. Freeze's buyout is approximately $20 million. AD John Cohen, who hired Freeze, has not publicly commented on the head-coach status since mid-October. The structural read is: a win at Texas A&M makes the Iron Bowl the deciding game; a loss makes the Iron Bowl an exit interview. McMurphy's piece said the quiet part: *"Auburn's institutional patience is not what it used to be. The buyout is steep but is not prohibitive. The 2026 cycle's most-likely SEC opening is here unless the next three weeks produce significantly different football than the past six have."*

**Mike Locksley, Maryland.** Year seven. 5-4 with three games remaining. The Big Ten's structural elevation that we tracked in the Big Ten Reasserting thread has been particularly difficult on Maryland, which has spent the past two seasons being the conference's second-worst program by S&P+ behind only Purdue. AD Damon Evans, who arrived in 2018 and has been Locksley's institutional partner throughout the run, has reportedly told a small circle of confidants that the program's competitive ceiling under Locksley has been reached. The buyout is approximately $14 million. The Maryland board's mood, on a long thread on TestudoTimes by user TerpInChief, has shifted from defensive of Locksley to resigned to a change. *"We are not winning the Big Ten,"* one reply read. *"We are barely even competing with the bottom half. The hire was the right hire in 2018. The program has not built what we hoped it would build. The change is overdue."*

**Lance Leipold, Kansas.** Year five. 5-4. Less hot than the others, but on the board because Kansas's improvement has plateaued and because the Big 12 has become more competitive than KU's structural ceiling can sustain. The buyout is small (~$7 million). The AD relationship is good. The most-likely scenario is Leipold finishes the season, gets a contract extension, and stays. The chapter is on the board because there is a 25% scenario in which Leipold takes a Power 4 opening that opens this cycle and Kansas does its own search.

**Dan Lanning, Oregon.** Not hot in the seat sense; on the board because Lanning's name is the name every premium program with an opening will start its search with. *"Lanning is the candidate of this cycle,"* Pete Thamel wrote in his ESPN Hot Board column on November 1. *"He is not leaving Oregon for a non-marquee opening. He may leave Oregon for a marquee opening. There are two or three programs in the country whose search would credibly include him. We will find out which two or three when the openings open."*

**Eli Drinkwitz, Missouri.** Year six. 7-2. Not on the seat-temperature board; on the candidate board because Drinkwitz is the SEC's most-watched second-tier head coach and because if a marquee SEC opening happens, his name will be on the short list. The Drinkwitz scenario is the chapter we will pick up if any of the following programs open: Auburn (most likely), LSU (low probability — Brian Kelly's seat is not actually hot in '25), Texas A&M (low probability — Mike Elko's first year went well), or Florida (medium probability — Billy Napier remains on the long-tail risk list).

**Billy Napier, Florida.** Year four. 5-4 with three games remaining. The board's longest-running narrative. Napier has survived three offseasons of "this is the cycle" speculation. The fourth one may be the cycle. AD Scott Stricklin has institutional patience that exceeds Auburn's; the patience is not infinite. If Florida loses two of its remaining three (at Ole Miss, Florida State, at Missouri), the cycle becomes the cycle. McMurphy's read: *"Napier's seat has been hot for two years and he is still here. The reason he is still here is that the alternative — the cost of a search, the buyout, the recruiting disruption — is not clearly better than the alternative of letting another year play out. That math may break this cycle. Vegas has Napier at 60% to be back."*

**Trent Bray, Oregon State.** Year two. 4-5. Not hot in the firing sense; the program is in the rebuild we noted in the Realignment Endgame thread when Oregon State and Washington State got left out of the Pac-12 expansion. The chapter is on the board because the program's structural condition is precarious enough that a poor season's ending could produce a forced change. Buyout is small. Probability is low.

**Sam Pittman, Arkansas.** Year six. 5-4. The board's quietest watch. Pittman's seat has been on the long-tail risk list since 2023. The program's ceiling under him has been set. The buyout is the structural protection. The 2026 cycle could be the cycle. Probably is not.

**Brent Pry, Virginia Tech.** Year four. 6-3. Not hot. On the candidate-board side because if a Power 4 opening happens, Pry's name will be in the second tier of conversations.

What we are watching for, in the next four weeks, is the kind of November we wrote up in the 12-Team Playoff Settling thread — the kind where structural elevation produces structural pressure on the bottom of programs' coaching ranks because the playoff math does not let underperformance compound. Eli Drinkwitz, in his media availability after the Missouri win at Mississippi State on November 1, said the line that Cover 3's Andy Staples called the most-honest thing said by a coach in October: *"Every November in this format is the November where everyone who isn't winning is about to lose their job. That is the format. The format is the format. We have to win in November."*

Chapter 2 picks this up after the Black Friday weekend, when the firings are likely to start.""",
        "byline": "From The Coaching Carousel · 2026-27 Department",
        "published_at": "2025-11-05 10:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "Action Network Hot Board", "url": None, "date": "2025-11-04"},
            {"kind": "beat-writer", "name": "Pete Thamel", "label": "ESPN Hot Board column", "url": None, "date": "2025-11-01"},
            {"kind": "podcast", "name": "Cover 3", "label": "(Andy Staples on Drinkwitz quote)", "url": None, "date": "2025-11-04"},
            {"kind": "board", "name": "TerpInChief", "label": "TestudoTimes thread", "url": None, "date": "2025-10-29"},
        ],
        "pull_quote": "Every November in this format is the November where everyone who isn't winning is about to lose their job. That is the format.",
    },
    {
        "chapter_number": 2,
        "title": "Black Friday Week: Three Firings, One Surprise, and the AD Phone Calls That Started Friday Morning",
        "dek": "Auburn fired Hugh Freeze on the morning after the Iron Bowl. Florida fired Billy Napier the same day. Maryland fired Mike Locksley the day before. The interim tags went up. The candidate phone calls started.",
        "body_markdown": """Black Friday week landed three firings in a 36-hour window: Maryland fired Mike Locksley on Wednesday morning, Florida fired Billy Napier on Friday morning, and Auburn fired Hugh Freeze on Saturday morning. The Locksley firing was the least-surprising of the three (we wrote it up as 70% probable in [Chapter 1](#chapter-1)). The Napier firing was higher than Vegas had it (which had been at 40% to fire). The Freeze firing was, on the timing alone, more sudden than the prevailing expectation, which had been that Auburn would let the dust settle from the Iron Bowl loss before formally moving. The dust did not settle. AD John Cohen made the call by 9am Saturday. The interim tags — Maryland's Mike Locksley → defensive coordinator Brian Williams; Florida's Billy Napier → offensive coordinator Russ Callaway; Auburn's Hugh Freeze → defensive coordinator Wesley McGriff — went up within hours.

What's worth tracking, beyond the firings themselves, is the candidate-board reordering that started Friday morning when the Florida news broke and accelerated through Saturday after the Auburn news. We picked up in [Chapter 1](#chapter-1) that Lanning, Drinkwitz, and Pry were the candidate-board names of the cycle. The Florida and Auburn openings put both programs in conversation with all three. Brett McMurphy, in his Saturday-evening Action Network update, had the names sourced cleanly: *"Florida's search firm has reached out, in the past 36 hours, to representatives for Dan Lanning, Eli Drinkwitz, Brent Pry, Lane Kiffin (yes, again), and James Franklin (provisionally — Penn State's CFP run will determine whether the conversation goes anywhere). Auburn's list has substantial overlap. The two programs are competing for the same six or seven names. The compression of the search timeline matters."*

The compression of the search timeline is the structural feature of the cycle nobody had quite priced. Auburn and Florida both have December early signing-day pressures — the cycle's marquee recruiting class commitments are largely settled by December 18, and a coaching search that runs past that date risks losing the recruits the new coach was hired to retain. Both programs have, in the past, taken three to four weeks to complete searches. Both programs need to finish in two. *"The compressed timeline favors the candidates with existing institutional momentum,"* Pete Thamel wrote in his Sunday-morning ESPN column. *"Lanning at Oregon, Drinkwitz at Missouri — these are coaches whose programs and contracts make a fast move possible. Coaches in less-mobile situations are at a real disadvantage in a two-week search. The cycle's compression is not neutral; it is shaping which candidates the programs can credibly land."*

The Cover 3 podcast (ep 348, December 1) ran the most-thorough postmortem of the firings on the Sunday afternoon after the Auburn news. Andy Staples and Danny Kanell ran through each firing and the post-firing landscape. *"Auburn's most likely hire is Drinkwitz,"* Staples said. *"Drinkwitz is from Atlanta originally. His agent is Jimmy Sexton. The program has institutional connections to the Sexton client base that go back twenty years. Florida's most likely hire is Lanning, and Florida is going to pay above market for the privilege. The structural question is whether Florida can outbid Oregon — Oregon has the institutional resources, the playoff trajectory, and a roster Lanning recruited. Florida has the SEC platform, the recruiting footprint, and the institutional desperation that occasionally produces a better deal than the rational valuation. We will find out within ten days."*

The boards in the affected programs were doing their own work in parallel. The Auburn board on AuburnSports, in a Saturday-night thread by user WarEagle1972 titled *"Now what"* that ran 1,400 replies in the first 18 hours, processed the firing with the institutional intensity that Auburn fanbase moments produce. *"Drinkwitz or bust,"* one reply read. *"If we don't get Drinkwitz, we are at risk of cycling through the same kind of hire we always cycle through. The program needs the candidate of this cycle, not the third-best candidate the search firm produces because the candidate of this cycle didn't take our call."* The dominant tone was anxious-but-engaged, which is the Auburn institutional default in a coaching search.

The Florida boards, on GatorCountry, were closer to relieved than anxious. The program had spent two years preparing for this firing and, when it landed, the board's emotional energy was directed at the question of who came next rather than at the question of whether the firing was justified. A thread by user GatorChomp1990 titled *"Lanning and we figure it out"* ran 900 replies and the dominant view was that the program needed to outbid Oregon for Lanning and that Scott Stricklin needed to commit institutional resources at a level that the program's recent searches had not committed. *"This is the cycle that fixes the program or doesn't,"* one reply read. *"Stricklin has to be aggressive. The buyout for Napier is steep. The buyout to land Lanning will be steeper. The math is the math. Pay the math."*

The Maryland boards, on TestudoTimes, had a different chapter. Locksley's firing was the program's first head-coach firing-for-cause since 2010. The TerpInChief thread we cited in [Chapter 1](#chapter-1) had been right that the firing was overdue. The post-firing thread — *"What we look like as an opening"* — was a more-realistic assessment of the program's structural position than the program's fans usually permit themselves. *"We are a Big Ten football opening,"* one reply read. *"That is the most-attractive part of the job. Beyond that, our facilities are mid-conference, our recruiting footprint is contested, our budget is not Penn State or Ohio State. The hire we make is going to be a young assistant from a Power 4 program or a sitting head coach from a successful Group of Five program. We are not getting Lanning. We are not getting Drinkwitz. We are getting someone whose first job this is, or whose last G5 job set this one up. Both can work. Neither is the candidate of the cycle."*

The next two weeks are when the chapters land. The Auburn search and the Florida search will produce hires by approximately December 12. The Maryland search will likely run into January. We pick this up in Chapter 3 after the hires are settled.""",
        "byline": "From The Coaching Carousel · 2026-27 Department",
        "published_at": "2025-12-02 11:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "Action Network update", "url": None, "date": "2025-11-30"},
            {"kind": "beat-writer", "name": "Pete Thamel", "label": "ESPN column", "url": None, "date": "2025-12-01"},
            {"kind": "podcast", "name": "Cover 3", "label": "Episode 348 (Staples + Kanell)", "url": None, "date": "2025-12-01"},
            {"kind": "board", "name": "WarEagle1972", "label": "AuburnSports thread", "url": None, "date": "2025-11-30"},
            {"kind": "board", "name": "GatorChomp1990", "label": "GatorCountry thread", "url": None, "date": "2025-11-29"},
        ],
        "pull_quote": "The cycle's compression is not neutral; it is shaping which candidates the programs can credibly land.",
    },
    {
        "chapter_number": 3,
        "title": "January: The Hires Settle, Lanning Stays, and the Auburn-Drinkwitz Surprise",
        "dek": "Florida hired James Franklin from Penn State. Auburn hired Eli Drinkwitz from Missouri (per the read). Maryland hired Indiana coordinator Tino Sunseri. The hires we wrote up as the cycle's most-likely outcomes were not the hires that landed.",
        "body_markdown": """The cycle settled in the second week of January with three hires that, taken together, produced a different chapter than the candidate boards we wrote up in [Chapter 1](#chapter-1) and [Chapter 2](#chapter-2) had projected. Florida hired James Franklin from Penn State on January 8 — a hire that became possible after Penn State's CFP semifinal loss, when Franklin and AD Patrick Kraft mutually concluded that the institutional plateau had been reached and that the next chapter of Franklin's career needed to be at a different program. Auburn hired Eli Drinkwitz from Missouri on January 11, completing the move that the Cover 3 pod had projected in [Chapter 2](#chapter-2) as the most-likely outcome. Maryland hired Tino Sunseri, the Indiana defensive coordinator and former Curt Cignetti deputy at JMU, on January 14 — a hire that the boards had not projected and that the program's search firm had clearly produced from the second tier of options.

We picked this thread up in [Chapter 1](#chapter-1) by writing that Lanning was the candidate of the cycle, and we picked it up in [Chapter 2](#chapter-2) by tracking Florida's pursuit of Lanning as the cycle's defining negotiation. The negotiation did not produce the outcome the boards had projected. Lanning, after a 72-hour window in which Florida reportedly offered him a contract approximately 30% richer than his existing Oregon deal, declined to leave. The reasoning, sourced cleanly by Pete Thamel in his ESPN column on January 7, was structural: *"Lanning concluded that Oregon's institutional resources, the program's recruiting trajectory, and the conference's structural elevation in the Big Ten gave him a higher-probability path to a national championship at Oregon than the SEC platform at Florida did. The conclusion was personal. The conclusion was also defensible by the math. Florida bid against an Oregon retention package that Oregon was prepared to fund at a level the boards in Eugene had not realized the program had the institutional ceiling to fund. Both bids were at the top of the market. Lanning chose the program he believed had the better roster."*

The Lanning decision freed up the timing for Florida to pivot to Franklin, which they did within 36 hours. The Franklin-to-Florida move had been on the long-tail watch list for years — Franklin's profile (longtime Power 4 head coach, established recruiter, Big Ten experience) is a clean fit for what Florida had spent two years searching for, and his contractual situation at Penn State allowed for a faster-than-usual move. The move surprised the Penn State boards in its abruptness but not in its substance. *"We knew this could happen,"* one Black Shoe Diaries reply read. *"Franklin had taken the program as far as he could without the breakthrough we have been waiting for. The breakthrough did not happen. The next coach inherits a roster Franklin built and a program whose ceiling has been demonstrated. We will see what they do with it."*

The Auburn-Drinkwitz move was the cleanest hire of the cycle and the one that played most exactly to the projection in [Chapter 2](#chapter-2). Drinkwitz, with Jimmy Sexton representing him, signed a six-year deal worth approximately $9.5 million per year. The buyout structure protects him through year four. The contract's recruiting-bonus and CFP-bonus structure are substantially richer than Auburn's previous coaching contracts, which signals an institutional commitment from John Cohen that the AD's prior critics on the boards had not fully credited him with being capable of. *"Cohen got the candidate he should have gotten,"* Brett McMurphy wrote in his summary on January 12. *"He paid market. He used the search firm efficiently. He did not get into a bidding war with Florida that would have driven the price up further. The Drinkwitz hire is, in candidate-quality terms, an A-minus hire. The contract terms are A-minus terms. The cycle's most-likely outcome happened in the way the most-likely outcome was supposed to happen."*

The Maryland hire — Sunseri at $4.2 million per year — was the cycle's structural outlier, and the one Bruce Feldman wrote about most carefully. *"Sunseri is a 38-year-old defensive coordinator with one season as a Power 4 coordinator (Indiana under Cignetti),"* Feldman wrote on January 15. *"His prior experience is as a JMU position coach and an FCS-level coordinator. The Maryland board had hoped for a name with more head-coaching experience. The board did not get it because the candidate pool that Maryland had genuine access to did not contain it. Sunseri is what Maryland's institutional position can credibly attract this cycle. The hire is a developmental hire. It will succeed or fail on whether Sunseri can scale the Cignetti playbook to a program with structurally weaker resources than Indiana had when Cignetti arrived. The bet is reasonable. The bet is also a bet."*

The Penn State opening — created by Franklin's departure to Florida — became the cycle's late-arriving fourth chapter. The program's search, run by AD Patrick Kraft with the search firm Korn Ferry, settled in late January on Manny Diaz, the Duke head coach who had built the Blue Devils into a credible ACC program over three seasons. The Diaz hire was substantially less surprising than the Sunseri hire to Maryland. The Penn State boards on Black Shoe Diaries received the hire with the characteristic mix of *"this could work"* and *"why not Lanning, why not Drinkwitz"* that has accompanied every Penn State coaching announcement since Franklin's hire in 2014. The thread by user NittanyLionForever titled *"Diaz it is"* ran 600 replies and the dominant view was guarded optimism. *"Diaz is a serious head-coaching hire,"* one reply read. *"He has built a program. The program he built is structurally smaller than Penn State, but the playbook scales. The hire is not the splashy hire we wanted. The hire is a substantive hire. We will see."*

The losers' bracket of the cycle — programs that whiffed on their preferred candidates and ended up with second-choice hires — included Maryland (we just wrote it up), Tulane (which had hoped for a Power-4-jumping G5 coach and ended up retaining its existing offensive coordinator as interim head coach pending a longer search), and James Madison (which had hoped to retain its head coach Bob Chesney through the cycle and lost him to a P4 OC opening at Wake Forest). The losers' bracket is the chapter the carousel always produces and that nobody outside the affected programs spends much time on. We are noting it because the chapters in this thread compound, and the losers' bracket of one cycle becomes the openings of the next.

The recruiting-class disruption — and we will track this as Chapter 4 lands in the spring — has been substantial. Florida's class, which had been ranked No. 12 going into Black Friday, fell to No. 19 by early February as Napier-recruited commits decommitted and Franklin had to rebuild. Auburn's, by contrast, held — Drinkwitz's reputation as a closer combined with the program's institutional commitment to retention work that Cohen had front-loaded as part of the Drinkwitz hire produced the kind of recovery McMurphy had projected as plausible. The Penn State class, in the chaos of the Franklin departure, is the chapter we cannot yet fully read. Diaz's first month will determine whether the program retains its top-fifteen class or rebuilds further down the rankings.

We pick this thread up in Chapter 4 in the spring of 2026 with the new hires settling, the recruiting classes finalized, and the early evidence on whether each hire is producing what the program hired the coach to produce.""",
        "byline": "From The Coaching Carousel · 2026-27 Department",
        "published_at": "2026-01-18 10:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Thamel", "label": "ESPN Lanning column", "url": None, "date": "2026-01-07"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "Action Network Drinkwitz summary", "url": None, "date": "2026-01-12"},
            {"kind": "beat-writer", "name": "Bruce Feldman", "label": "The Athletic Sunseri analysis", "url": None, "date": "2026-01-15"},
            {"kind": "board", "name": "NittanyLionForever", "label": "Black Shoe Diaries Diaz thread", "url": None, "date": "2026-01-22"},
        ],
        "pull_quote": "Lanning chose the program he believed had the better roster.",
    },
    {
        "chapter_number": 4,
        "title": "Spring 2026: Drinkwitz at Auburn, Franklin at Florida, and the Early Evidence on Whether the Hires Are Producing",
        "dek": "Three months in. Drinkwitz is closing on the recruiting class Auburn needed. Franklin is rebuilding Florida's class while installing his program. Diaz at Penn State is mostly invisible, which is what year one of any rebuild should look like.",
        "body_markdown": """The spring of 2026 — three months after the cycle's hires settled in [Chapter 3](#chapter-3) — has produced the kind of early-evidence chapter that this thread was built to track. The hires are now installed. The recruiting classes are signed. The spring practices are happening. The early reads on whether each program is going to produce what the program hired the coach to produce are starting to be readable in the way they always start to be readable in late April, after spring games, before the summer-program work begins.

**Drinkwitz at Auburn** has been the cycle's success story so far. The recruiting class, after the Black Friday-week disruption we tracked in [Chapter 2](#chapter-2), finished at No. 6 nationally — Auburn's highest finish since 2017. Drinkwitz personally landed three five-stars who had been previously committed to other SEC programs (one from LSU, one from Texas A&M, one from Tennessee). The institutional commitment Cohen had front-loaded into the hire — the contract structure, the NIL collective coordination, the on-campus recruiting infrastructure — had produced the recovery McMurphy projected and slightly exceeded it. The boards on AuburnSports, where WarEagle1972's *"Now what"* thread from [Chapter 2](#chapter-2) had set the program's anxious tone, were processing the spring with a more confident register. *"Drinkwitz is doing the job we hired him to do,"* one reply on a March thread read. *"The class is real. The portal additions are real. The staff is what we wanted. The next data point is the season itself. The first three months are as good as they could have been."*

The portal moves Drinkwitz made — and we are tracking these because the cycle's portal additions tell a structural story about how each new coach is building — have been targeted: a graduate-transfer quarterback (from Boise State, in the Hank Bachmeier-replacement chair Mountain West programs have spent the past four years figuring out), an OL out of the Big Ten (a former four-star who had been buried at Iowa for two years and saw the playing-time path at Auburn as the right move), and a wide receiver from Indiana who had played for Cignetti the year before. The portal additions are recognizably Drinkwitz's portal additions — high-floor, position-of-need, transferable culture. The portal-architecture-as-coaching-specialty thread that we have written about across the wider Coaching Carousel discourse is, at Auburn, being practiced at a level the program has not previously demonstrated.

**Franklin at Florida** has been the cycle's rebuild story. The recruiting class, which had cratered to No. 19 by early February as we wrote in [Chapter 3](#chapter-3), recovered to No. 13 by the late February signing window — a meaningful improvement but not the top-eight finish Florida had been targeting before Napier's firing. The institutional disruption of the coaching change had cost the program approximately five spots of recruiting-class quality, which translates to perhaps four to six players who would have signed if Napier had been retained. Franklin's first month at Florida was spent entirely on retention and re-recruiting; the structural rebuild of the program's identity has been pushed into spring practice. *"Franklin is doing the work in the order he has to do it,"* GatorChomp1990 wrote in a March thread. *"The class first. The staff second. The identity third. He has spent his entire career building programs in this order. The work will take all of 2026 to install. The program will not be a Franklin program until 2027 at the earliest. We knew this when we hired him. The hire was always the hire that produced 2027 results, not 2026."*

That sober expectation-setting, on the boards, is the chapter Florida has needed. The program's institutional habit of expecting immediate results from every hire has been, by most beat-writer accounts, the single biggest impediment to building the kind of long-arc program the SEC's structural elevation now requires. The Franklin hire's structural advantage is that Franklin's track record is for long-arc programs — at both Vanderbilt and Penn State, he produced his best work in years three through six. The boards' patience-on-display in the spring threads is the institutional precondition the program needed.

**Diaz at Penn State** has been the cycle's invisible chapter, in a way that is widely interpreted as positive. The new head coach has been low-profile through the spring: no major staff changes after the initial hires (Diaz brought his Duke offensive coordinator and his defensive coordinator), no dramatic portal moves (a quarterback from Coastal Carolina, a running back from Wake Forest, three OL from G5 programs), and a recruiting class that Franklin had signed in the December early signing period and Diaz held intact through February. *"Year one of a rebuild should be invisible,"* Pete Sampson wrote in his March column on the program. *"Diaz is doing what year one needs him to do. The visible chapter starts in August when his actual program plays its first game."* The Black Shoe Diaries threads on Diaz, in the spring, have been notably less anxious than they were in the immediate aftermath of Franklin's departure. *"Diaz is the coach,"* one reply read. *"He is doing year one stuff. We are seeing what we need to see. The next hire we evaluate is whoever we hire after Diaz, in five or seven years. That is a long time from now. We will let him cook."*

**Sunseri at Maryland** has been the cycle's developmental chapter. Three months in, the program's recruiting class finished at No. 38 — slightly below the program's recent floor and substantially below the program's institutional aspiration. The portal moves have been small. The staff hires (Sunseri brought his Indiana defensive line coach and is building out the rest of the staff with a mix of MAC head coaches and FCS coordinators) have been competent rather than splashy. The spring practices, which the boards have processed with the patience of fans who knew this would be a slow rebuild, have produced the kind of early reports that suggest the program is being properly installed. *"We hired a developmental coach,"* one TerpInChief reply read in March. *"He is doing developmental work. The program will not be Indiana for at least three years. The program will be a credibly-coached Big Ten program by year two. We will see if the cycle pays off."*

The losers'-bracket programs from [Chapter 3](#chapter-3) — Tulane, James Madison, the smaller G5 openings that had to compete for second-tier candidates — have settled. Tulane hired the JMU OC who had replaced Bob Chesney's departed coordinator (the cascade is real). JMU promoted from within. The cycle's full chapter is now closed.

What this thread is going to track, going forward, is the next cycle. The 2026 in-season hot board will start populating in late summer. The structural conditions that produced the 2025-26 cycle — the CFP pressure, the SEC/Big Ten elevation, the AD class's institutional permission to make changes — are not going away. The 2026-27 cycle will have its own chapters. We will write them as they land.

In the meantime: Drinkwitz at Auburn is the early winner, Franklin at Florida is the long-arc bet, Diaz at Penn State is the invisible install, Sunseri at Maryland is the developmental project. The cycle produced the chapters the cycle was always going to produce. The chapters that follow them are the work of the seasons to come.""",
        "byline": "From The Coaching Carousel · 2026-27 Department",
        "published_at": "2026-04-23 11:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2, 3],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic Diaz column", "url": None, "date": "2026-03-12"},
            {"kind": "board", "name": "WarEagle1972", "label": "AuburnSports March update thread", "url": None, "date": "2026-03-08"},
            {"kind": "board", "name": "GatorChomp1990", "label": "GatorCountry March thread", "url": None, "date": "2026-03-15"},
            {"kind": "board", "name": "TerpInChief", "label": "TestudoTimes spring thread", "url": None, "date": "2026-03-21"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "Action Network spring carousel update", "url": None, "date": "2026-04-10"},
        ],
        "pull_quote": "Drinkwitz is doing the job we hired him to do. The class is real. The portal additions are real. The staff is what we wanted.",
    },
]
