"""ND-USC: A Rivalry Recalibrating — chapter seeds (Notre Dame voice register)."""
THREAD_SLUG = "nd-usc-rivalry-recalibrating"

CHAPTERS = [
    {
        "chapter_number": 1,
        "title": "November 30, 2024: 49-35 in the Coliseum, and the Series Survives First Contact With Realignment",
        "dek": "Riley Leonard's senior year, USC's first year as a Big Ten member, and a meeting that proved the rivalry could still bear the weight that ninety-six previous meetings had placed on it.",
        "body_markdown": """The 96th meeting of Notre Dame and USC was played on the night of November 30, 2024, in the Coliseum, under the lights, with USC in its first year as a Big Ten member and Notre Dame in the middle of a College Football Playoff push that none of the preseason projections had quite ranked them to be capable of. Notre Dame won 49-35. Riley Leonard ran for two touchdowns and threw for three. Marcus Freeman, in his third season as head coach, beat his West Coast counterpart Lincoln Riley for the second time in three meetings. The rivalry — which the rest of college football had spent the previous summer asking whether it could survive realignment, the schedule's structural pressure, and the sheer competitive asymmetry of two programs whose recent histories had been moving in opposite directions — survived its first post-realignment test.

That the rivalry needed to survive a test is the institutional fact this thread is starting from. The history is the history: 96 meetings going back to 1926, when Knute Rockne's Notre Dame and Howard Jones's USC began an annual series that has paused only twice (the World War II years and a brief COVID-related schedule disruption in 2020). The rivalry has produced three Heisman winners playing in it, two title-implication losses for Notre Dame in the past two decades, the 2005 *Bush Push* game that South Bend has never quite finished processing, and the 2017 49-14 ND win that flipped the narrative momentum of the post-Kelly era as the program was being rebuilt. The rivalry is, as Eric Hansen of the South Bend Tribune wrote in his preview piece on November 27, *"the only rivalry in college football in which both programs measure themselves against the rivalry itself, not against the rest of the schedule. ND-USC is its own argument. It always has been."*

The argument the rivalry was making, in the November 2024 meeting, was about whether the series's competitive equilibrium could be maintained when one of the two programs (USC) had moved into a structurally bigger conference and the other (Notre Dame) had stayed independent. The question had a thousand sub-questions. Did USC's coaching investment under Riley still match the institutional commitment Notre Dame brings to its football program? Did Notre Dame's recruiting, structurally constrained by independence and academic standards that the SEC and Big Ten do not share, still produce the players who could compete with USC's roster? Did the games still mean what they had meant? The November 30 meeting answered the third question affirmatively. The first two are still being worked out.

The on-field details mattered. Riley Leonard, the Duke transfer who had spent the previous offseason being the most-discussed quarterback story of the spring (we will track this more in Chapter 2's recap of the season's broader CFP arc), played the kind of game that South Bend now expects of its quarterbacks: 19 of 27 for 247 yards passing, 24 carries for 142 yards rushing, decisive in the red zone, in command in the two-minute. The numbers were not the story. The story was the way Leonard played the third quarter — three touchdown drives in five possessions, an offensive identity that had been opaque for most of the early season suddenly clarifying into the kind of clear, fast-tempo, run-pass-option attack that Marcus Freeman had wanted his offense to play since he was hired. Tyler Horka at The Athletic, who has covered Notre Dame closely, wrote that *"Leonard finally became the quarterback Freeman recruited him to be in the third quarter of the USC game. The fourth quarter was Leonard managing what the third quarter had built. That is the most-quarterback-y sequence in his Notre Dame career."*

USC's defensive collapse — and "collapse" is the right word; the Trojans had been within 28-21 at the half — was the story Antonio Morales at The Athletic USC pulled apart in his postgame coverage. *"Lincoln Riley's defense is being asked to win games in November against opponents that play physical, mid-tempo, conventional offense,"* Morales wrote. *"USC's defense, schematically, has not been built for that. The defense Riley brought from Oklahoma was built for shootouts. ND-USC was not a shootout. The conference USC just joined will produce a lot more games that aren't shootouts. The mismatch the November 30 game exposed is structural, not personnel-driven, and it is the work USC has to do this offseason."*

The boards' processing was instructive. On BlueGrayGold, GoldRush89's autopsy thread *"49-35 in the Coliseum"* ran 940 replies and the dominant tone was institutional satisfaction in a register that is recognizably Notre Dame's: not gloating, not triumphalist, but the specific kind of contained-pride that the program's voice has carried for a hundred years. *"We won. We won the way Notre Dame wins. We did it on the road in their building in their first year of being a Big Ten program. The series is what it has always been. Standards inherited, never costumes worn,"* one reply read. The Standards-inherited line, which is the program's institutional mantra and the line the Notre Dame profile has built its voice around, hit at exactly the right moment in the postgame for it to have read as performative if it hadn't read as exactly true.

On WeAreSC, the thread *"What just happened to our defense"* by user TrojanLifer ran 700 replies and the dominant tone was a more-direct unhappiness than USC fans had been comfortable expressing publicly since Riley arrived. *"We hired Lincoln Riley to win games like the one we just lost,"* one reply read. *"We did not hire him to lose them at home to a team whose coach we beat to the punch on hiring three years ago. The defensive coordinator change is going to be the offseason's only legitimate question. The other questions are smaller versions of that question."*

The series's institutional context — and this is the framing we are going to track for chapters — is that ND-USC has been the cleanest case study available for what happens to a rivalry when one half of the rivalry is in a structurally bigger competitive ecosystem than the other. Notre Dame is independent. USC is now a Big Ten member. The schedule pressures on both programs have changed. The 2024 game was, on the schedule, a regular November Saturday for Notre Dame and a *strategically scheduled* late-November game for USC, who had the opportunity to schedule it earlier and chose to keep it where ND-USC has historically lived. That choice — USC's choice — was what made the November 30 game possible. USC could have moved it. USC did not. That decision, which Antonio Morales flagged in his preview as *"the most institutionally important decision Lincoln Riley made this calendar year,"* preserves the rivalry on the calendar.

This thread is going to track that. Chapter 2 picks it up after Notre Dame's CFP run.""",
        "byline": "From The ND-USC: A Rivalry Recalibrating Department",
        "published_at": "2024-12-02 10:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Eric Hansen", "label": "South Bend Tribune preview", "url": None, "date": "2024-11-27"},
            {"kind": "beat-writer", "name": "Tyler Horka", "label": "The Athletic ND postgame", "url": None, "date": "2024-12-01"},
            {"kind": "beat-writer", "name": "Antonio Morales", "label": "The Athletic USC postgame", "url": None, "date": "2024-12-01"},
            {"kind": "board", "name": "GoldRush89", "label": "BlueGrayGold autopsy", "url": None, "date": "2024-12-01"},
            {"kind": "board", "name": "TrojanLifer", "label": "WeAreSC thread", "url": None, "date": "2024-12-01"},
        ],
        "pull_quote": "We won the way Notre Dame wins. Standards inherited, never costumes worn.",
    },
    {
        "chapter_number": 2,
        "title": "January: The CFP Run, the Title Game, and the Rivalry's Stakes Recontextualized",
        "dek": "Notre Dame made the title game. USC finished 7-6. The asymmetry is the chapter that the November meeting could not yet show.",
        "body_markdown": """Notre Dame's 2024 season ended in Atlanta on a Monday night in late January when Ohio State beat them 34-23 in a College Football Playoff title game that, for the first three quarters, the Irish had a credible path to winning. The loss was Notre Dame's deepest CFP run since the program made the title game against Alabama in the 2012 season. The loss was also, structurally, the moment that recontextualized the November 30 meeting we wrote up in [Chapter 1](#chapter-1) — because the meeting that had read at the time as a strong win for Notre Dame against a peer rival now read as a strong win for the program that would be playing for a national championship six weeks later, against the program that ended its season 7-6 and would spend the offseason firing its defensive coordinator.

The asymmetry is the chapter the November meeting could not yet show. ND-USC has been the most balanced of college football's elite cross-regional rivalries for ninety-eight years partly because the two programs have generally been operating at similar competitive levels. The 2024 season's verdict was that they were not. Notre Dame was a top-three program in the country. USC was a top-thirty program with a top-five roster and structural problems on defense that no November meeting could quite expose because the November meeting had been a shootout-with-an-Irish-running-clock and the structural problems only show when the Trojans can't outscore them.

The CFP run itself — and we are going to be brief because the run has been documented at length in the broader 12-Team Playoff thread — went through Indiana, Georgia, and Penn State before arriving in Atlanta. Each game produced the kind of moment Notre Dame fans had been hoping the program could produce in a postseason for a decade. The Indiana win was clean. The Georgia win, in New Orleans on January 1, was the program's most-significant postseason victory since the 2012 BCS Championship loss; Riley Leonard ran for the touchdown that broke the game open, and the Notre Dame defensive front (Howard Cross III, Jordan Botelho, Rylie Mills) won the line of scrimmage in a way that had not happened to Georgia's offense in two seasons. The Penn State semifinal was won late, on a missed field goal Penn State should have made. The title game against Ohio State was tight through three quarters and got away in the fourth on Jeremiah Smith's third-quarter touchdown, which the Notre Dame secondary will spend the offseason watching.

What this did to the program's institutional self-image was the chapter Eric Hansen of the South Bend Tribune wrote on January 22, the morning after the title game. *"Notre Dame's run to the national championship game produced two simultaneous outcomes,"* Hansen wrote. *"It validated everything Marcus Freeman has been building. It also confirmed that the program is still one tier of executional consistency away from winning the kind of game it played Monday night. Both things are true. The fanbase has spent the past 24 hours processing both at once."* The line read accurately. The boards on BlueGrayGold processed it accurately too. GoldRush89, returning to the same byline that had run the November 30 autopsy in [Chapter 1](#chapter-1), wrote: *"We made the title game. We did not win the title game. The program in 2025 will be measured against both facts. We are not who we were a year ago. Our time is now is more than a slogan again. We have to live up to it."*

The Our-time-is-now line is the program's institutional mantra and the line the Notre Dame profile has built its identity-phrase architecture around. We noted in [Chapter 1](#chapter-1) that the Standards-inherited line read as exactly true after the USC win. The Our-time-is-now line, after the title game, read with a different weight — less performative, more demanding. The slogan had been a question for most of the past decade. The 2024 season made it look like the right answer. The fact that the season ended one win short of validating it is the structural pressure the program will carry into 2025 and beyond.

USC's parallel processing, on WeAreSC, was a much more direct version of unhappiness than Notre Dame's. We noted in [Chapter 1](#chapter-1) that TrojanLifer had been pointed about the defense after the November loss. The post-season thread *"7-6 in year three"* by user PoinsettiaPete ran 1,100 replies in the week between Christmas and New Year's and the dominant view was that the program had a hire-or-fire-the-coordinator decision to make and a recruiting-class-not-keeping-up problem to solve. *"Lincoln Riley is a top-five offensive coach in college football,"* one reply read. *"He is not a top-twenty defensive program-builder, and what he was hired to do here was build a program, not run an offense. The November 30 game was the single best evidence of the gap between what we hired him to do and what he is doing. The gap is not closing on his current trajectory."*

The recruiting evidence has supported the boards' anxiety. USC's 2025 cycle finished No. 18 nationally — the program's lowest finish since 2017. Notre Dame's, by contrast, finished No. 6 — the program's highest finish since 2013. The recruiting-cycle gap, like the structural-quality gap the season had exposed, has widened. Antonio Morales wrote a tough USC offseason column in early February that captured the institutional consensus: *"Lincoln Riley has the off-season to fix the defense, retain his staff for offensive continuity, and hold the recruiting class. If he does all three, he buys himself a real 2025. If he does two, he buys himself a survivable one. If he does one, the conversation about whether USC's investment is producing returns becomes a conversation USC's administration will need to be ready to have."*

What this does to the rivalry, going forward, is the question Chapter 3 will pick up. The 2025 meeting is in South Bend in November, on Notre Dame's terms, with the program coming off a CFP final and USC coming off — depending on what 2025 produces — either a recovery year or a decision-year. The series can absorb asymmetry; the series has absorbed asymmetry before. The 2017 49-14 ND win, which we noted in [Chapter 1](#chapter-1), was an asymmetry win. So was 2005, in the other direction. The series carries weight even when the programs aren't peers. The structural question is whether the asymmetry that 2024 exposed becomes a multi-year condition or a one-cycle data point.""",
        "byline": "From The ND-USC: A Rivalry Recalibrating Department",
        "published_at": "2025-01-25 11:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Eric Hansen", "label": "South Bend Tribune title-game column", "url": None, "date": "2025-01-22"},
            {"kind": "beat-writer", "name": "Antonio Morales", "label": "The Athletic USC offseason column", "url": None, "date": "2025-02-04"},
            {"kind": "board", "name": "GoldRush89", "label": "BlueGrayGold post-title-game thread", "url": None, "date": "2025-01-22"},
            {"kind": "board", "name": "PoinsettiaPete", "label": "WeAreSC offseason thread", "url": None, "date": "2024-12-30"},
        ],
        "pull_quote": "Our time is now is more than a slogan again. We have to live up to it.",
    },
    {
        "chapter_number": 3,
        "title": "October 2025: The South Bend Meeting, the Rivalry's Schedule Survives Another Year",
        "dek": "USC visited South Bend on a Saturday in late October. ND won, again, by a margin that closed in the fourth quarter. The series's structural condition entered its second year of post-realignment testing.",
        "body_markdown": """The 97th meeting of Notre Dame and USC was played on October 18, 2025, in Notre Dame Stadium, on a Saturday afternoon kickoff that ABC put as its 3:30pm Eastern game-of-the-week. Notre Dame won 24-17. The score was closer than the November 30, 2024 meeting we wrote up in [Chapter 1](#chapter-1), which is the structural data point the chapter is built around. USC, which had spent the offseason firing its defensive coordinator and replacing him with D'Anton Lynn (the UCLA defensive coordinator who had been on the short list of every blue-blood program looking for a defensive hire that cycle), played a defense in October 2025 that bore no resemblance to the defense it had played in November 2024. The program had, in the structural sense, done one of the three things Antonio Morales had laid out as the offseason agenda in [Chapter 2](#chapter-2). The other two — staff continuity on offense, recruiting-class retention — had also been substantially achieved.

The meeting itself was a chapter in the series's institutional life. Notre Dame, defending its 2024 CFP-final season, was 6-0 entering the game and ranked third in the AP poll. USC, in the better version of the recovery year Morales had teed up, was 5-1 with the lone loss being a tight conference road game in late September that the program had played credibly. The game played as a peer-on-peer game in a way the November 2024 meeting had not. The Notre Dame win was, technically, decisive (24-17) and emotionally, contested (USC had two fourth-quarter possessions inside the Notre Dame 35 that came up empty). The series, which we suggested in [Chapter 2](#chapter-2) was structurally tested by the asymmetry of 2024, demonstrated in October 2025 that the test was a one-cycle data point rather than a multi-year condition. The asymmetry had narrowed.

What had narrowed it was the work USC had done in the offseason. Lincoln Riley, in his first major decision after the 7-6 finish, hired Lynn to coordinate the defense. Lynn brought the schematic identity (multiple-front, single-high coverage, more press at the line) that the conference had been demanding USC develop. The Trojans' defense in 2025 was meaningfully better than the defense in 2024 — not elite, but credible. The credibility was what the rivalry's structural condition required. *"USC played a defense Saturday that the program could not have played twelve months ago,"* Antonio Morales wrote in his postgame column. *"The work in the off-season was real. The work has not finished. The program is closer to being a peer than the November 2024 game suggested. It is also still not at the level of the program's stated ambition. The October 2025 game was a checkpoint, not a destination."*

The Notre Dame side of the chapter — and we are tracking this with the program-voice register that has held throughout the thread — was a quieter version of institutional satisfaction. The team had won. The team had not dominated. The team had been pushed and had pushed back. Eric Hansen's South Bend Tribune column the day after the game opened with the kind of measured Notre Dame line that the boards have always responded to: *"Notre Dame won the way the program is supposed to win. The way the program won this game was the program's identity, sustained against an opponent that had improved enough to make the win earned. Both halves of that sentence matter."* The boards on BlueGrayGold processed the line as accurate. GoldRush89's third installment in the rivalry-thread series — *"97 meetings and counting"* — ran 580 replies and the dominant tone was the institutional pride that does not gloat. *"USC was better today than they were last November,"* one reply read. *"We were better today too. The series is what it has always been. Standards inherited."*

The Standards-inherited refrain — which we have carried through every chapter of this thread, and which we noted in [Chapter 1](#chapter-1) as the Notre Dame profile's institutional mantra — has earned its repetition. The line is doing real work. The work is the work of articulating what the program means by its institutional voice in moments that test whether the voice still holds. The October 2025 meeting tested it. The voice held. The Notre Dame fanbase, on the boards and in the postgame, used the line because the line was the most accurate available description of what the rivalry had just produced.

The schedule's structural future is the chapter we have to flag. The 2026 meeting is on the schedule. So is 2027. So is 2028. USC's contractual obligations to the Big Ten require the program to play nine conference games per year; the rest of its schedule, three games, has historically included Notre Dame, a non-conference Power 4 game, and a non-conference Group of Five game. The structural pressure on Notre Dame's slot has been a topic of conversation in USC's athletic department for the past 18 months — several reporters, including Bruce Feldman in his February 2025 column, have noted that *"the conversation about whether USC's Notre Dame commitment can survive a poor stretch of the program's competitive cycle is a real conversation, even if it is not a likely outcome in the next contract cycle."* The next contract cycle is 2030. Until then, the schedule holds.

The boards have noticed the conversation and have responded with the institutional disinterest that the rivalry's history earns. *"USC will play Notre Dame as long as USC wants to be USC,"* one BlueGrayGold reply read. *"If USC stops playing Notre Dame, USC stops being USC. The program's identity has Notre Dame in it. Removing Notre Dame from the schedule is removing the rivalry that defines the program's national posture. Lincoln Riley knows this. Jen Cohen knows this. The schedule will hold."*

That is the position Chapter 4 will pick up at, in the spring of 2026, with the schedule held and the rivalry's structural condition entering its third post-realignment year.""",
        "byline": "From The ND-USC: A Rivalry Recalibrating Department",
        "published_at": "2025-10-21 09:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Eric Hansen", "label": "South Bend Tribune postgame", "url": None, "date": "2025-10-19"},
            {"kind": "beat-writer", "name": "Antonio Morales", "label": "The Athletic USC postgame", "url": None, "date": "2025-10-19"},
            {"kind": "beat-writer", "name": "Bruce Feldman", "label": "The Athletic February column", "url": None, "date": "2025-02-12"},
            {"kind": "board", "name": "GoldRush89", "label": "BlueGrayGold thread", "url": None, "date": "2025-10-19"},
        ],
        "pull_quote": "We were better today too. The series is what it has always been. Standards inherited.",
    },
    {
        "chapter_number": 4,
        "title": "Spring 2026: The Series Holds, the Programs Diverge Again, and the Rivalry's Future Is the Schedule's Discipline",
        "dek": "Two cycles of post-realignment ND-USC are in the books. The series is intact. The future depends on whether USC and Notre Dame keep deciding it should be intact.",
        "body_markdown": """Spring of 2026 finds the ND-USC series in the same place every elite cross-regional rivalry eventually finds itself: structurally durable but contingently scheduled, dependent on the two programs' continued institutional commitment to keep the matchup on the calendar each year. The 2025 season closed with Notre Dame finishing 11-2 and missing the CFP semifinal in a quarterfinal loss to Texas; USC finished 9-4 and made the bracket as the No. 11 seed, where the program lost in the first round to Tennessee at home. The asymmetry that we wrote up in [Chapter 2](#chapter-2) has compressed but has not closed. USC is closer to peer status than the Trojan program of November 2024 was. Notre Dame is structurally elevated relative to where the program had been before Marcus Freeman's title-game run. The series is being played by two programs whose competitive levels are different but no longer dramatically so.

Marcus Freeman, in the third year of the head-coaching run that we have tracked across these chapters, has now produced two consecutive seasons of CFP-level work. The 2024 season ended in Atlanta. The 2025 season ended in the quarterfinals to Texas, in a game that Notre Dame led at the half and lost in a fourth quarter that Texas's offensive front controlled. The two seasons together — and we noted in [Chapter 2](#chapter-2) that GoldRush89 had written that the program was *"not who we were a year ago"* — have established the program's institutional ceiling at a level South Bend has not consistently operated at since the Lou Holtz era. *"We are now a program whose ceiling is the College Football Playoff every year,"* one BlueGrayGold reply in a January 2026 thread read. *"That is a different program than the one we have been since 1993. The work to operate at that ceiling is the work of every offseason from now on. Our time is now is no longer aspirational. It is the actual standard."*

USC's spring, parallel to Notre Dame's, has been the chapter Antonio Morales has been writing in installments for two years. *"USC has done the work,"* he wrote in his March 2026 column. *"The defense under Lynn is now structurally credible. The offense under Riley is, as it always has been, elite. The recruiting class for 2026 finished No. 9 nationally — the program's best class since 2018. The program is no longer in the conversation about whether Riley's hire is producing returns. The program is in the conversation about whether the returns will produce a Big Ten title and a CFP semifinal, which is the standard the program has been operating to since the moment it joined the Big Ten."*

What this does to the November 2026 meeting — which is in South Bend, on the regularly-scheduled date, with both programs entering as preseason top-fifteen teams — is that it produces the chapter ND-USC has not yet had in the post-realignment era: the meeting between two peer-quality programs, both of whom have legitimate playoff stakes, both of whom carry the institutional weight the rivalry has historically carried. We noted in [Chapter 1](#chapter-1) that ND-USC was the only rivalry in college football in which both programs measured themselves against the rivalry itself, not against the rest of the schedule. The 2026 meeting will be the first one since 2017 in which both programs are also being measured against the broader playoff race. That is a different kind of stakes. That is the stakes the rivalry has been wanting to find again.

The schedule's structural future is the chapter that does not write itself. The contractual situation we flagged in [Chapter 3](#chapter-3) — that USC's 2030 contract cycle is the next moment when the Notre Dame slot could come under structural pressure — has not changed. What has changed is the institutional mood inside USC's athletic department. Jen Cohen, in a March interview with Pete Sampson at The Athletic that received unusual amplification in the rivalry's beat coverage, said: *"Notre Dame is on our schedule because Notre Dame should be on our schedule. The conversations we have about non-conference scheduling start with Notre Dame and then move outward. That is the program's institutional position. That position is not currently under review."* The line read as a deliberate institutional reassertion. The boards on WeAreSC processed it as such. *"The series is safe through this contract cycle,"* one reply read. *"The next cycle starts in 2030. The conversations about that cycle start in 2028. We have time. The program's leadership is on the right side of this question. The program's fans are on the right side of this question. As long as both stay on the right side, the series stays on the schedule."*

The boards on BlueGrayGold, in a March 2026 thread by GoldRush89 titled *"Where the rivalry stands"*, ran 320 replies and the dominant tone was the institutional patience that the program's voice has carried through the thread. *"The series has had asymmetric moments before,"* one reply read. *"It had them in the late 1990s when USC was rebuilding from the post-Smith era. It had them in the Charlie Weis years when Notre Dame was rebuilding from itself. The asymmetric moments do not last. The series is older than any of us. The series will outlast all of us. Standards inherited. We will be there in November 2026. We will be there in November 2030. The schedule holds."*

What this thread is going to do, going forward, is treat the rivalry as the institutional case study it has always been: the rivalry that two programs choose to keep playing because the rivalry's institutional value is greater than any single season's competitive logic. ND-USC has been an institutional choice for ninety-eight years. The post-realignment chapters have tested whether the choice would survive in its modern form. Two cycles of testing have produced the answer: yes, structurally, the choice survives. The schedule is the discipline. The programs' continued mutual commitment is the practice of the discipline.

We pick this thread up after the 2026 meeting. The chapter to come is the one where the two programs play each other as competitive peers for the first time in nearly a decade, with the Big Ten's structural elevation in the conference's back pocket and Notre Dame's CFP-level institutional status as the program's defining identity. November is six months away. We will be there.""",
        "byline": "From The ND-USC: A Rivalry Recalibrating Department",
        "published_at": "2026-04-22 10:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2, 3],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Antonio Morales", "label": "The Athletic USC March column", "url": None, "date": "2026-03-08"},
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic (Jen Cohen interview)", "url": None, "date": "2026-03-19"},
            {"kind": "board", "name": "GoldRush89", "label": "BlueGrayGold March thread", "url": None, "date": "2026-03-22"},
            {"kind": "board", "name": "TrojanLifer", "label": "WeAreSC reply on Cohen interview", "url": None, "date": "2026-03-20"},
        ],
        "pull_quote": "The series is older than any of us. The series will outlast all of us. Standards inherited.",
    },
]
