"""Realignment Endgame — chapter seeds."""
THREAD_SLUG = "realignment-endgame"

CHAPTERS = [
    {
        "chapter_number": 1,
        "title": "The Week the Pac-12 Stopped Being a Conference",
        "dek": "Washington and Oregon to the Big Ten. Arizona, ASU, Utah to the Big 12. Cal and Stanford to the ACC. The conference that produced more Heisman winners than any other broke apart in 96 hours.",
        "body_markdown": """The Pac-12 had been dying for a year. Most of college football's beat writers had been writing the obituary in installments since USC and UCLA announced their departures to the Big Ten in the summer of 2022. What happened the first week of August 2023 was not the death itself; it was the moment the death became simultaneous and irreversible. Washington and Oregon were announced as Big Ten members on August 4. Arizona, Arizona State, and Utah moved to the Big 12 within the same news cycle. Cal and Stanford ended up in the ACC by September. By the time the dust settled — and by "dust" we mean television contracts, broadcast rights, scheduling commitments, and a hundred and ten years of league identity — the Pac-12 had two members. Two. Washington State and Oregon State, the institutions that did not get a chair when the music stopped, were left to negotiate their own future essentially alone.

The blow-by-blow has been ably documented by the people who covered it in real time — Pete Thamel at ESPN broke most of the meaningful timeline, Brett McMurphy at Action Network broke the rest, Jon Wilner at the San Jose Mercury News did the local work nobody else could. We are not relitigating the timeline; we are setting the table for a thread we are going to track for years. The Pac-12's collapse is not the end of realignment. It is the first dramatic instance of a process that is going to keep producing chapters as long as the underlying economics — broadcast rights, conference distributions, the College Football Playoff revenue pool — keep tilting toward two superconferences.

Greg Sankey, in a moment that read at the time as gloating and reads in retrospect as accurate, told reporters in Birmingham on August 7 that *"the conference structure of college football has been bending toward two leagues for fifteen years, and what happened this week didn't cause the bend, it just made it visible."* It is hard to find anyone in the sport who disagrees with the substance of that read. What people disagree on is the consequences.

The consequences for the Pac-12's diaspora are mixed at best. Oregon and Washington, which have national-brand status and were going to land somewhere good no matter what happened, drew the longest end of the stick. They will travel, but they will travel to good destinations and they will be paid Big Ten distributions to do it. Cal and Stanford, with smaller national footprints and a coastal isolation problem the ACC's geography does not solve, will travel further to play for less. The boards in Berkeley and Palo Alto have been remarkably circumspect about the move; the local assumption seems to be that this is a decade-long experiment whose alternative was insolvency.

The consequences for the broader sport are clearer. Tony Petitti, then six months into his Big Ten commissioner role, told ESPN's Heather Dinich on August 6 that *"we set out to build the best conference in college sports, and we believe this expansion is the next chapter of that work."* Translated into less-careful language: the Big Ten is now a coast-to-coast league with sixteen-and-soon-to-be-eighteen members and a media-rights deal that the SEC will spend the next half-decade trying to match. The competitive gap between the SEC + Big Ten and everyone else is now wider than it was 10 days ago.

The reactions on the boards mapped to the schism cleanly. On TideFans, a thread by user TideRollerSC titled *"Pac-12 dies and Bama is fine but"* worked through what the reorganization meant for SEC programs structurally. The dominant read was relief mixed with low-grade dread: relief that the SEC was not the conference being raided, dread that the Big Ten had just made a credible bid to become the more-attractive league for west-coast recruiting in a way the SEC has never had to worry about before. *"We just got a real competitor for the first time since the BCS started,"* one reply summarized. *"Roll Tide, but our recruiting board for 2026 is going to look different in a hurry."*

In Eugene, the BoardOfProspects thread *"What we just joined"* was 600 replies of Oregon fans working through the trade-off. *"We left a conference that was on its way to dying and joined a conference that was on its way to winning,"* one reply read. *"That's a good trade. The travel is going to be a story we tell our grandkids about. We won't tell them the part where we missed our 8am Eastern kickoffs against Penn State. We will tell them about the Saturday in November when the Big House was full for our visit."*

Jon Wilner's column in the Mercury News on August 8 — the most-read realignment piece of the week, by a long way — landed on a quieter note. *"What we lost this week,"* he wrote, *"was a hundred-and-ten-year tradition of West Coast college football having its own house, and being able to govern itself in that house. What we got in exchange is a series of Saturday games against opponents most of our fans have not been raised to care about. The math may pencil out. The grief, for the people who had grown up in the Pac, is real and is not going to be erased by the math."*

We are starting this thread now because the chapters that follow this one are going to span years. The ACC's situation is not stable. The Big 12 is more stable than people think but is still in the middle of a two-decade reinvention. The SEC and Big Ten will continue to grow and to consolidate. The Pac-12's two-school remnant has to figure out what to do next — there is talk of rebuilding the conference around former Mountain West programs, talk of formal dissolution, talk of a Pac-2-as-affiliate arrangement with another conference. None of those paths is finished. Each will produce its own chapter.

What we are tracking is the slow-motion endgame of a process that the Pac-12's collapse made unavoidable. Chapter 2 picks up about a year in.""",
        "byline": "From The Realignment Endgame Department",
        "published_at": "2023-08-09 14:00:00",
        "read_time_minutes": 7,
        "referenced_chapter_ids": [],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Thamel", "label": "ESPN", "url": None, "date": "2023-08-04"},
            {"kind": "beat-writer", "name": "Jon Wilner", "label": "San Jose Mercury News", "url": None, "date": "2023-08-08"},
            {"kind": "beat-writer", "name": "Heather Dinich", "label": "ESPN (Petitti interview)", "url": None, "date": "2023-08-06"},
            {"kind": "board", "name": "TideRollerSC", "label": "TideFans thread", "url": None, "date": "2023-08-07"},
        ],
        "pull_quote": "We just got a real competitor for the first time since the BCS started. Roll Tide, but our recruiting board for 2026 is going to look different in a hurry.",
    },
    {
        "chapter_number": 2,
        "title": "One Year In: The Travel, the Television, and the Tony Petitti Calendar",
        "dek": "Twelve months after the announcement, the Big Ten's coast-to-coast experiment is producing the data its critics warned about. The data is not, on its own terms, fatal — but it is producing chapters its architects did not write into the pitch.",
        "body_markdown": """The Big Ten played its first season as a coast-to-coast conference in the fall of 2024. UCLA flew to State College for an October Saturday and back to Westwood the next morning. Oregon flew to Madison in late September and got beat. USC played Penn State, Maryland, Washington, and Notre Dame in a six-week stretch that included two trips of more than 2,000 miles. The travel did exactly what people said it would do: it tired teams out, it produced jet-lagged practices, it cost money. What it also did, less predictably, was produce the kind of scheduling friction that is forcing the conference to redesign how it allocates Saturdays.

We picked up this thread in [Chapter 1](#chapter-1) by noting that the Big Ten's coast-to-coast bid was the most consequential of the realignment moves because it set up a media-rights race the SEC would spend half a decade trying to match. One year in, the SEC has not matched it. The SEC's TV deal is still richer per-team in the short term, but the Big Ten's structural advantage — coast-to-coast inventory, four time zones of broadcast windows, a 12pm Eastern kickoff that doesn't compete with East Coast NFL Sunday morning — is starting to show in advertising rates. Tony Petitti, in a January interview with The Athletic's Pete Sampson, was characteristically measured: *"We knew the inventory was the asset. We did not know how quickly the inventory would price."* The line read at the time as a victory lap. It read accurately.

The friction the conference did not fully plan for has been on the schedule itself. The Big Ten's expansion meant that the conference now has 18 schools across four time zones, and the schedule has had to accommodate a series of competing demands: travel parity, TV-window distribution, traditional rivalries, and the new coast-to-coast pairings the conference's media partners want to feature. The result, as Pete Sampson laid out in The Athletic on November 14, is *"a schedule template that has more variables than any conference has ever tried to solve for, and a series of compromises that are visible to anyone reading the actual matchups."* Specifically: USC played four East Coast road games in 2024. Penn State played three West Coast games. The Big Ten's traditional rivalry game protections (Michigan-Ohio State, Iowa-Wisconsin, Penn State-Ohio State) survived but at the cost of cross-divisional matchups that fans had been counting on for decades.

The boards in the conference have catalogued the friction. The 11Warriors thread *"Tony's calendar is impossible"* in November ran 720 replies and worked through every scheduling complaint Ohio State fans had about the season. The dominant complaint was not about Ohio State's own schedule, which was protected; it was about what the schedule had cost in terms of conference identity. *"We used to play Wisconsin every year. We used to play Michigan State every year. We used to play Iowa every other year, max,"* one reply read. *"Now we play Maryland, Rutgers, USC, and Washington in a five-week stretch and we miss two of those traditional matchups. The conference is bigger and feels smaller."*

The SEC, meanwhile, ran its first season with Texas and Oklahoma as members in 2024. Greg Sankey's Birmingham media remarks in July had teed up the integration as *"the most natural addition any league has ever absorbed,"* and the on-field season largely vindicated the framing. Texas made the College Football Playoff. Oklahoma fell short. Both schools' addition to the conference produced predictable second-order effects on recruiting, schedule difficulty, and TV ratings — all positive for the league. The friction that mattered, in the SEC, was less about geography (Texas and Oklahoma are not coastal) and more about competitive depth. Sankey's challenge for the conference is not the integration; it's the fact that the league now has 16 teams, three or four of which can credibly contend for a playoff bid in any given year, and the conference championship game in this format becomes mathematically less central than it used to be.

Heather Dinich at ESPN tracked the broader picture in late November 2024 and made the case that *"the realignment of 2023 has produced exactly the bifurcated league structure that the realignment was designed to produce. The SEC and Big Ten now operate as the only two conferences with a structurally durable claim to playoff slots in the new bracket. The ACC, Big 12, and the wreckage of the Pac-12 are operating in a tier below, with the auto-bid for conference champions as their only structurally guaranteed access."* That framing has held. It held through the first 12-team selection. It held through the second.

Where the chapter gets harder is on the ACC. As we flagged in [Chapter 1](#chapter-1), the ACC was structurally unstable when realignment hit. It is more unstable now. Florida State's lawsuit against the conference, filed in late 2023, has been working its way through North Carolina courts for over a year. The Grant of Rights — the contractual lock keeping ACC members in the conference through 2036 — is the lawsuit's central target. If FSU prevails, or if the conference settles in a way that meaningfully weakens the GOR, the ACC's path to the next round of consolidation opens up. Clemson, which filed its own related suit in 2024, is the second domino. Brett McMurphy at ALON has been writing this beat with the kind of rigor it requires; his thesis, in his most recent column, is that *"the ACC is functionally negotiating its own dismemberment, and the only question is whether the dismemberment is sudden or staged."*

The Big 12, the conference everyone left for dead in summer 2023, has been the surprise of this thread so far. Brett Yormark's media deal with ESPN and Fox, signed in October 2022 just before the BYU/UCF/Cincinnati/Houston additions, turned out to be more flexible and more revenue-generative than analysts predicted at the time. The Big 12's per-school distributions in 2024 were within 15% of the ACC's, with significantly more upside in the next negotiation. The conference is not vulnerable to poaching the way the Pac-12 was, because the conference's value is structurally tied to a TV market that the SEC and Big Ten have already saturated in their existing footprints. *"The Big 12 has accidentally become the third stable conference in college football,"* Andy Staples said on Cover 3 (ep 296, October 2024). *"Three months after the apocalypse, that is not the read anyone had."*

Chapter 3 picks up at the moment the FSU/Clemson lawsuits enter their next procedural phase. We will know more, in 2025, about what the next domino actually looks like.""",
        "byline": "From The Realignment Endgame Department",
        "published_at": "2024-11-19 09:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic (Petitti interview)", "url": None, "date": "2024-01-08"},
            {"kind": "beat-writer", "name": "Pete Sampson", "label": "The Athletic schedule analysis", "url": None, "date": "2024-11-14"},
            {"kind": "beat-writer", "name": "Heather Dinich", "label": "ESPN", "url": None, "date": "2024-11-22"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "ALON column", "url": None, "date": "2024-11-15"},
            {"kind": "podcast", "name": "Cover 3", "label": "Episode 296 (Andy Staples)", "url": None, "date": "2024-10-21"},
            {"kind": "board", "name": "11Warriors thread", "label": "Tony's calendar is impossible", "url": None, "date": "2024-11-12"},
        ],
        "pull_quote": "The Big 12 has accidentally become the third stable conference in college football. Three months after the apocalypse, that is not the read anyone had.",
    },
    {
        "chapter_number": 3,
        "title": "The Middle Game: ACC Lawsuits, the SEC Whispers, and the Yormark Surprise",
        "dek": "Eighteen months after the Pac-12 broke, the realignment process has moved out of the headline phase and into the litigation phase. The litigation phase is slower, less photogenic, and more determinative.",
        "body_markdown": """The middle game of realignment is being played in courthouses and conference-room meetings rather than in news conferences, and the cadence of news has slowed accordingly. The Florida State and Clemson lawsuits have crawled through the North Carolina court system at the speed lawsuits crawl. The SEC and Big Ten have not announced a single new member in 18 months, which is the longest stretch of structural stillness in college football since 2019. And in the absence of headline moves, the second-order story — what each conference is doing inside its own footprint to prepare for the next move — has become the actual story.

We picked this thread up in [Chapter 2](#chapter-2) by noting that the ACC is functionally negotiating its own dismemberment. Eighteen months later, the dismemberment hasn't happened, but the negotiation has gotten more visible. Florida State's case against the ACC entered a key procedural phase in March 2025. The conference's argument, restated by Jim Phillips at the conference's spring meetings, is that the Grant of Rights is enforceable through 2036 and that any unilateral departure would trigger penalties of approximately $130 million per program. FSU's argument, restated by AD Michael Alford in late February, is that the GOR's revenue-distribution model has become so structurally inequitable that the contract has effectively been breached by the conference itself. Both arguments have merit. Neither has been resolved.

What has happened, while the lawsuits crawl, is that the SEC and Big Ten have done preparatory work. Pete Thamel reported in early February that *"both conferences have done extensive scenario planning around an ACC scenario, including formal evaluations of which programs would be invited under various dissolution conditions. The work is not the same as a commitment, but it is also not nothing."* The Athletic's Bruce Feldman backed the same reporting in March. The whisper-network conclusion, which a number of beat writers have been carrying for months, is that an SEC scenario where the conference adds Florida State, Clemson, North Carolina, and Virginia is the most-frequently-modeled outcome. The Big Ten scenario, where the conference adds North Carolina, Virginia, Miami, and Notre Dame in a partnership-or-membership configuration, is the second-most-modeled. *"The work is being done because the work has to be done,"* Feldman wrote. *"The conferences are not going to be caught flat-footed when the lawsuit produces an outcome."*

The Big 12's continued surprise stability has been the chapter that nobody outside the conference predicted. As we flagged in [Chapter 2](#chapter-2), Brett Yormark's TV deal turned out to be more durable than analysts expected. The next round of evidence on this came in February 2025, when Yormark announced a private-equity exploration partnership with CVC Capital that would, if it lands, infuse the conference with capital that no other conference has access to in the same form. The boards in the Big 12's footprint have read this as either *"smart financial engineering that secures our future for a generation"* (the optimistic Texas Tech / Iowa State view) or *"the conference selling its soul to a hedge fund because the TV deal isn't actually as good as Yormark says it is"* (the pessimistic Oklahoma State / Cincinnati view). Both reads have evidence. Neither has been settled.

What's happened to the leftover Pac-12 — Washington State and Oregon State, plus the affiliate moves the schools have orchestrated with the Mountain West — has been the quieter chapter. The two schools, working with conference commissioner Teresa Gould (who took over the Pac-12 office in late 2023 specifically to manage the wind-down), have signed scheduling alliances with the Mountain West that effectively let them play a Pac-12-branded football schedule in 2024 and 2025 without operating as a full conference. The plan, announced in fall 2024, is to formally rebuild the Pac-12 around former Mountain West programs (Boise State, San Diego State, Colorado State, Fresno State, and others) starting in 2026. Whether that conference can compete for an auto-bid in the new bracket is the open question. *"The new Pac is going to be a real conference,"* Boise State AD Jeramiah Dickey told the Idaho Statesman in January, *"but it is also going to be a conference that is reinventing itself in real time. The first three years are going to be hard. The first three years are also going to be ours."*

The boards in the affected schools have been quietly enthusiastic. A thread on a Boise State board called *"What we get and what we lose"* ran 200 replies in February and the dominant view was that the conference identity gain (Boise State as a Pac-12 program in name, with the institutional credibility that label still carries even after the league's collapse) outweighed the loss of the Mountain West's familiar grind. *"We are not Big Ten,"* one reply read. *"We were never going to be Big Ten. The Pac-12 was always the realistic ceiling for what this program could aim at. We are going to live in that ceiling now."*

The chapter that has not yet been written is the Notre Dame chapter. As we noted in [Chapter 1](#chapter-1), Notre Dame's independence has been the single durable constant of the realignment cycle. The university's contract with NBC, its scheduling alliance with the ACC for non-football sports, and its position in the College Football Playoff revenue distribution have collectively given the program no structural reason to give up independence. That is starting, very quietly, to shift. The CFP's new revenue distribution model — which rewards conference performance more heavily than the old model — has begun to make independence financially less attractive in scenarios where Notre Dame underperforms. The whispers from South Bend, restated by Pete Sampson on his Locked On Notre Dame podcast (ep 412, March 12), are that *"the program is not actively negotiating with the Big Ten or anyone else, but the program is also not pretending the math is the same as it was five years ago."* That is the most movement on the Notre Dame question that has happened in two decades.

The middle game's defining feature is that it is happening in slow motion. The lawsuits will produce outcomes. The SEC and Big Ten will move when those outcomes land. The Big 12 will continue to surprise people who underestimated Yormark. The Pac-12-as-Mountain-West-affiliate will or will not work. And Notre Dame's quiet recalculation will, eventually, produce its own chapter.

Chapter 4 picks up two cycles in.""",
        "byline": "From The Realignment Endgame Department",
        "published_at": "2025-06-08 11:15:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Pete Thamel", "label": "ESPN", "url": None, "date": "2025-02-04"},
            {"kind": "beat-writer", "name": "Bruce Feldman", "label": "The Athletic", "url": None, "date": "2025-03-11"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "ALON FSU/ACC update", "url": None, "date": "2025-03-22"},
            {"kind": "beat-writer", "name": "Idaho Statesman (Jeramiah Dickey interview)", "label": "Boise State AD remarks", "url": None, "date": "2025-01-30"},
            {"kind": "podcast", "name": "Locked On Notre Dame", "label": "Episode 412 (Pete Sampson)", "url": None, "date": "2025-03-12"},
        ],
        "pull_quote": "The conferences are not going to be caught flat-footed when the lawsuit produces an outcome.",
    },
    {
        "chapter_number": 4,
        "title": "Spring 2026: The ACC Settles, Yormark Holds, and Notre Dame Stays Independent for Now",
        "dek": "Three realignment chapters compounding. The ACC's lawsuit settled in March. The Big 12's PE deal closed in February. Notre Dame extended its independence agreement with NBC. The endgame is no longer a singular event; it is a steady-state condition.",
        "body_markdown": """The realignment story has, in the spring of 2026, reached the strange place where its central uncertainties have been replaced by structural facts that nobody is fully comfortable calling "settled." The ACC's lawsuit with Florida State settled in March on terms that ESPN's Brett McMurphy summarized as *"a partial weakening of the Grant of Rights, a meaningful redistribution of revenue toward FSU and Clemson, and an explicit acknowledgment that the conference's existing structure cannot survive another decade without further modification."* That is not the dissolution outcome the SEC and Big Ten had been modeling. It is, plausibly, a slower path to the same destination. We picked this thread up in [Chapter 3](#chapter-3) by noting that the conferences had done preparatory work for an ACC dissolution scenario; what they did not do work for, because the work had not been visible from the outside, was the slower-decay scenario the lawsuit's settlement actually produced.

What this means in practice: FSU and Clemson are not leaving the ACC in 2026. They are not leaving in 2027. The settlement gives both programs a structurally larger share of conference revenue, a clearer path to a future opt-out (the GOR is now enforceable only through 2030, not 2036), and a contractual mechanism for renegotiation if conference revenue trails the SEC and Big Ten by more than a defined threshold. Both programs gain optionality. Both programs lose the certainty of a near-term move. The ACC, meanwhile, has bought four years of stability at a cost that will reshape its internal economics. *"The settlement is the worst possible outcome for everyone,"* one ACC AD told Bruce Feldman last week, on background, *"and it is the most likely possible outcome we were ever going to get to. The conferences that bought it can live with it. They cannot live with it forever."*

The Big 12's CVC Capital deal closed in February 2026, on roughly the terms Yormark had floated in 2025. The conference's per-school distributions are now projected to land within 8% of the ACC's, with the PE infusion specifically earmarked for facilities investment, NIL collective support, and conference-level branding work. As we noted in [Chapter 3](#chapter-3), the boards split on this; the optimistic read has been broadly vindicated by the early implementation. The pessimistic read — that PE money carries strings that will manifest in a few years — has not been disproven, but it has also not been demonstrated. *"We bought time,"* Yormark told The Athletic's Sam Khan Jr. in February. *"We bought it on terms we can defend. The next conversation about the Big 12's future will happen on different ground than the last one did, because of this."*

Notre Dame, for its part, extended its independent-football arrangement with NBC through 2032 in late January. The extension was not a surprise — the financial logic for independence has not fundamentally changed — but the terms of the extension were notable. NBC's annual rights payment to ND was reportedly increased by approximately 18%, with explicit language allowing the program to participate more flexibly in conference scheduling alliances during the contract term. The most-cited reading of the language is the Pete Sampson read on Locked On Notre Dame (*ep 488, February 14*): *"The university has reaffirmed its independence and has also given itself a mechanism to revisit the question, on its own timeline, in the back half of the contract. That is the most economically rational thing the university could have done."*

The boards in South Bend reacted with a relief that was, in places, almost grateful. A thread on BlueGrayGold called *"Independence: extended"* by GoldRush89 ran 480 replies and the dominant tone was a reassertion of the program's distinct identity against a realignment cycle that has consumed nearly every other historic independent. *"We watched Penn State stop being independent in '93,"* one reply read. *"We watched Miami stop in '91. We watched BYU stop in '23. We are still independent. We are the last one standing in the way the program has always told itself it should be standing. That matters more than the math."*

What we picked up in [Chapter 1](#chapter-1) — that the Pac-12's collapse was the first dramatic instance of a process that would keep producing chapters — has held. The chapters have kept landing. The pace has slowed. The drama has migrated from press conferences to court filings to PE-deal closings to NBC contract extensions, and the drama in those venues is harder to write about than the drama in press conferences was. But the underlying process is unchanged: the consolidation of the sport's economics into two superconferences continues, and the institutions that fall outside the two-conference center continue to negotiate the terms on which they exist alongside it.

What has changed, two cycles after the Pac-12's collapse, is the timeline. The endgame is no longer a singular event. It is a steady-state condition. The ACC has bought four years. The Big 12 has bought a generation. The Pac-12-rebuild is in its third year and is still figuring itself out. Notre Dame has bought another six years of independence. The next round of meaningful structural change will land sometime between 2028 and 2032, depending on which conference's media deal expires first and which conference's discontent reaches political mass first.

This thread is going to keep updating. The next chapter is probably the SEC's response to the ACC settlement — there are whispers, sourced in a Brett McMurphy column from April 14, that the conference is exploring a "premium membership" structure that would reward the four or five highest-revenue programs differently from the rest. If those whispers harden into negotiation, that becomes Chapter 5. We will pick this up when it does.

In the meantime: the realignment endgame continues. It is no longer dramatic. It is no longer settled either.""",
        "byline": "From The Realignment Endgame Department",
        "published_at": "2026-04-22 13:45:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2, 3],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "ALON FSU/ACC settlement summary", "url": None, "date": "2026-03-19"},
            {"kind": "beat-writer", "name": "Bruce Feldman", "label": "The Athletic (anonymous AD source)", "url": None, "date": "2026-04-15"},
            {"kind": "beat-writer", "name": "Sam Khan Jr.", "label": "The Athletic (Yormark interview)", "url": None, "date": "2026-02-21"},
            {"kind": "podcast", "name": "Locked On Notre Dame", "label": "Episode 488 (Pete Sampson)", "url": None, "date": "2026-02-14"},
            {"kind": "board", "name": "GoldRush89", "label": "BlueGrayGold thread", "url": None, "date": "2026-01-29"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "ALON premium-membership whispers", "url": None, "date": "2026-04-14"},
        ],
        "pull_quote": "The settlement is the worst possible outcome for everyone, and it is the most likely possible outcome we were ever going to get to.",
    },
]
