"""The Saban-to-DeBoer Transition — chapter seeds (Alabama voice register)."""
THREAD_SLUG = "saban-to-deboer"

CHAPTERS = [
    {
        "chapter_number": 1,
        "title": "January 10. The Standard Did Not Retire.",
        "dek": "Nick Saban retired on a Wednesday. Kalen DeBoer was hired on a Friday. What was being inherited was not the roster.",
        "body_markdown": """Nick Saban retired on the afternoon of January 10, 2024. The announcement was made by the university, not by the head coach himself, which is the kind of detail Bama people noticed in the moment and have not stopped noticing in the eighteen months since. The Standard does not retire. The man who articulated it for seventeen years did. Those are different sentences. The work of separating the two is what this thread is going to track, and the work is going to take years.

What was being inherited, when Greg Byrne picked up the phone the morning of January 11 and started the search, was not the roster. The roster was excellent. The roster always is. What was being inherited was a definition of what Alabama means to itself — the thing every coach Saban ever beat eventually figured out: that the program had stopped being a coaching job and become an institution that the coaching job served. The next coach was going to inherit the institution. The institution would not be inherited the same way the roster would.

The candidate list was reported in real time and the reporting was unusually accurate. Brett McMurphy at Action Network had Lane Kiffin on Wednesday night, then off it by Thursday morning. ESPN's Pete Thamel had Mike Norvell as a serious second-tier name through Thursday. Joe Goodman at AL.com — the indispensable Bama beat — had Kalen DeBoer's name surfacing by late Thursday and confirmed by Friday morning. The hire was announced Friday night. The total elapsed time between Saban's retirement and DeBoer's introduction was 56 hours.

The choice surprised nobody who had been watching DeBoer for two years and surprised nearly everyone else. The Washington job had been a quiet revelation. DeBoer had taken the program from 4-8 in his first year (2022) to 14-1 and a national championship game appearance in his second (2023), with a quarterback (Michael Penix Jr.) and an offense that played a register Bama hasn't played since maybe Sark's coordinator years. The criticism, immediately, was that DeBoer had never built a program — he had inherited one and accelerated it. Whether that mattered, in the context of inheriting a program built more thoroughly than any program in modern football, was the question Joseph Goodman framed in his AL.com column the morning after the hire: *"DeBoer didn't get the job because he was the safest pick. He got it because the safest pick was the wrong pick. Bama didn't need continuity. Bama needed someone who could think about the program from the outside in."*

The historical echo was Bear Bryant to Ray Perkins in 1983. The echo did not hold for long. Perkins inherited a program at the end of an era; DeBoer was inheriting one at the height of one. The closer comp, ironically, was Saban's own 2007 hire — coming in to replace a generational coach (Mike Shula's predecessor, the wreckage of the Mike Price hire, the post-Stallings interregnum) at an institution that had spent two decades watching its identity slip. The 2007 hire took years to become the 2009 title. This 2024 hire was being asked to keep the title in-house essentially without interruption.

The boards reacted with the contained intensity that's recognizable as Bama's institutional voice. TideRollerSC, the most-cited TideFans long-poster, opened a thread on Saturday morning titled *"What we just hired"* that ran 1,200 replies in 48 hours. The dominant tone was not panic. The dominant tone was assessment — a measured, somewhat exhausting working-through of every available data point on DeBoer, with occasional brief acknowledgments that the program had just lost the man who had defined its modern era. *"He won at Sioux Falls. He won at Fresno State. He won at Washington. He's going to win here,"* one reply read. *"Whether he keeps the Standard is the only question. The Standard is not a thing you can teach. We will find out."*

The Cole Cubelic morning show on WJOX in Birmingham captured a different tonal register the following Monday. Cubelic, who has been doing the morning show in Bama country for the better part of a decade, opened the show with: *"Nick Saban built the church. Kalen DeBoer is the new pastor. The church doesn't change. The pastor's job is to keep the church standing while the congregation gets used to a different voice in the pulpit."* The church-and-pastor framing was widely shared, including by people who weren't sure they liked it. It was, more than anything else said in that first week, the framing that captured what Bama was actually working through.

What was already clear by the end of the first week, which Aaron Suttles at the Tuscaloosa News noted on January 17, was that the staff transition was going to be the harder lift than the head-coach transition. Saban's coordinators (Tommy Rees on offense, Kevin Steele on defense) were not staying. DeBoer was bringing Ryan Grubb from Washington as offensive coordinator and was looking at Kane Wommack as a defensive option (he eventually got Wommack from South Alabama). The new staff would have, at most, six weeks to be in place before signing day finalized and spring practice began. Suttles' line was the one we keep returning to: *"Saban hired Saban-staff people. DeBoer is hiring DeBoer-staff people. The choice is not wrong. The choice is consequential. The Standard will continue to be the standard. What enforces the Standard, day to day, is changing."*

That is the thread we are going to track. Roll Tide. The first chapter is the announcement; the chapters that follow are about whether the institution survives the change in pulpit voice.""",
        "byline": "From The Saban-to-DeBoer Transition Department",
        "published_at": "2024-01-18 10:00:00",
        "read_time_minutes": 7,
        "referenced_chapter_ids": [],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Joseph Goodman", "label": "AL.com column", "url": None, "date": "2024-01-13"},
            {"kind": "beat-writer", "name": "Brett McMurphy", "label": "Action Network coaching board", "url": None, "date": "2024-01-11"},
            {"kind": "beat-writer", "name": "Aaron Suttles", "label": "Tuscaloosa News", "url": None, "date": "2024-01-17"},
            {"kind": "tv-radio", "name": "Cole Cubelic", "label": "WJOX morning show", "url": None, "date": "2024-01-15"},
            {"kind": "board", "name": "TideRollerSC", "label": "TideFans thread", "url": None, "date": "2024-01-13"},
        ],
        "pull_quote": "Nick Saban built the church. Kalen DeBoer is the new pastor. The church doesn't change.",
    },
    {
        "chapter_number": 2,
        "title": "August: First Camp Under DeBoer, and the Things You Can Already See",
        "dek": "Eight months in. The portal worked. The coordinator hires are settling. The OL is the question. The practices are not the practices Saban ran, and that is on purpose.",
        "body_markdown": """Eight months after the hire we wrote up in [Chapter 1](#chapter-1), DeBoer's first fall camp opened in Tuscaloosa with the kind of muted scrutiny that only ever attaches to the most-watched programs in the sport. Every period of every practice the media was permitted to watch was filmed, parsed, written up, and re-watched on TideFans within the hour. The big questions had been the right ones. The portal, as Saban famously did not love, was now a structural feature of how DeBoer was building the roster. Ryan Grubb was running the offense. Kane Wommack was running the defense. Jalen Milroe was the quarterback. The OL was the question.

The portal moves had been the cleanest signal of what kind of program DeBoer wanted to run. Bama added 15 players through the spring portal window — including, importantly, two starting-caliber offensive linemen (Parker Brailsford from Washington and Jaeden Roberts from Houston) and a starting wideout (Caleb Odom from a small school nobody had heard of, who has been the practice-report sensation of camp). The Saban-era Bama portal philosophy had been minimalist: take the player we've identified as a need, take only that player, do not over-portal. DeBoer's philosophy, articulated in his first-year media-day Q&A and visible in the actual moves, is *"we will use the portal to upgrade roster spots that are not at the level Bama needs them to be at, and we will not be precious about the number."* The number, in the spring window, was 15.

The boards processed this in real time with the patience of people who had been watching Bama recruit at a different cadence for seventeen years. A long thread on TideFans titled *"15 in. What it means"* by user CrimsonAndCool ran 800 replies and the dominant view was cautious: *"DeBoer is buying himself the roster he needs to compete this year, not the roster Saban would have been comfortable with. We will see if it pencils. The OL portal moves are the ones that have to hit. If they hit, we are fine. If they don't, the season turns on it."*

Aaron Suttles in the Tuscaloosa News, who has the longest institutional memory on the program of any beat writer working today, wrote the most-careful evaluation of camp on August 12. *"DeBoer's practices are not Saban's practices,"* he wrote. *"They are shorter. They are more position-group-focused. The team-period work is more competitive in tone — DeBoer wants the offense and defense actually trying to beat each other, in a way Saban's late-career camps had moved away from. The conditioning at the end is similar. The teach-everything-twice rigor of the install is similar. The vibe is different. The vibe is on purpose."* The vibe-on-purpose line is the one we keep coming back to. It is what we noted in [Chapter 1](#chapter-1) about DeBoer being asked to think about the program from the outside in. Eight months later, the outside-in thinking is showing up in the day-to-day texture of the building.

The Joseph Goodman counterpoint, in his AL.com column the same week, was that the vibe shift carried risk. *"Saban's late-career practices were what they were because Saban had figured out, over fifteen years, what the optimal load on a championship-caliber team actually was,"* Goodman wrote. *"DeBoer is not necessarily wrong to do something different — he has earned the right to coach his way. But the optimal load that produced six titles in fifteen years is not a thing you change without consequences. We will find out which consequences. We will find out by November."*

Wommack on defense has been the more-scrutinized hire of the two coordinator additions. The Saban-era Bama defense was a very specific philosophical product: pattern-match coverage with rare zone variations, six-man pressure rotations, and a structural commitment to never giving up explosive plays even at the cost of a slightly soft underneath profile. Wommack's defense at South Alabama was not that. Wommack's defense was more aggressive on the front, more willing to play single-high coverage with corners on islands, and more inclined to live with explosive plays in exchange for negative-play creation. The bet, articulated by Suttles after a Wednesday press session, is that *"the personnel Bama recruits is good enough to play either philosophy. Wommack is going to play the one he believes in. Whether that produces the Bama defensive identity fans recognize is the question. The early camp work suggests the answer will be: similar enough to Bama, different enough to be Wommack."*

The OL question, which we flagged in [Chapter 1](#chapter-1) as one of the inherited issues that would test DeBoer's first cycle, is — at the start of fall camp — the question we still don't have an answer to. The Saban-era OL development pipeline produced first-round picks at a clip nobody else in college football matched; that pipeline has not yet been demonstrated to be portable to a coordinator change, an OL coach change (Eric Wolford, the new OL coach DeBoer hired from a brief Notre Dame stop, has Saban-tree credentials but is his own teacher), and a roster that has portal-additions playing alongside Saban-era-recruited returning starters. The first three games of the season — Western Kentucky, USF, at Wisconsin — should give us early evidence. The Wisconsin game especially, because Wisconsin's front is the kind of Big Ten front that exposes OL questions the way SEC fronts don't always.

What we noted in [Chapter 1](#chapter-1) — that the Standard would continue to be the standard — has held through camp in the obvious sense. Bama still acts like Bama. The recruiting board is unchanged in its top-tier targets. The institutional discipline is unchanged. What's different is the day-to-day texture. The vibe is different. The vibe is on purpose. The season is six weeks away. We will know much more by then.""",
        "byline": "From The Saban-to-DeBoer Transition Department",
        "published_at": "2024-08-15 09:00:00",
        "read_time_minutes": 7,
        "referenced_chapter_ids": [1],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Aaron Suttles", "label": "Tuscaloosa News camp report", "url": None, "date": "2024-08-12"},
            {"kind": "beat-writer", "name": "Joseph Goodman", "label": "AL.com column", "url": None, "date": "2024-08-13"},
            {"kind": "beat-writer", "name": "Aaron Suttles", "label": "Tuscaloosa News (Wommack press session)", "url": None, "date": "2024-08-14"},
            {"kind": "board", "name": "CrimsonAndCool", "label": "TideFans thread", "url": None, "date": "2024-08-09"},
        ],
        "pull_quote": "DeBoer's practices are not Saban's practices. The vibe is different. The vibe is on purpose.",
    },
    {
        "chapter_number": 3,
        "title": "11-2, the Vandy Loss, and the First Verdict",
        "dek": "First-year DeBoer finished 11-2 with an SEC Championship loss and a CFP appearance. By any other program's standard, a triumph. By Bama's, a question. The Vandy loss specifically.",
        "body_markdown": """The first verdict on the Saban-to-DeBoer transition came in around 11:30pm Central time on a Saturday in October when Vanderbilt — Vanderbilt — beat Bama 40-35 in Nashville on a play-action touchdown pass to a tight end whose name Bama fans had to look up. The loss was not the season's defining moment in a literal sense; the season had eleven more games in it, including an SEC Championship Game, a College Football Playoff first-round bye, and a quarterfinal appearance against Notre Dame in the Sugar Bowl that Bama lost on a controversial fourth-down spot. But the Vandy loss was the moment the boards admitted that the transition was, in its first year, going to test the program in a way the program had not been tested in two decades.

We picked this up in [Chapter 2](#chapter-2) by noting that the OL question was the inherited issue DeBoer had not yet demonstrated he could solve. The Vandy loss was, in part, an OL loss. Bama could not run the ball when it needed to (1.7 yards per carry in the second half), could not protect Milroe in two-minute (Milroe was sacked four times and hit eight more), and could not extend two of three fourth-quarter drives that, with the kind of Saban-era short-yardage execution Bama had spent fifteen years making routine, would have flipped the game. The film told the story. The boards read the film. *"We are losing games we used to win because we can't get a yard,"* TideRollerSC posted in his Sunday-morning autopsy thread. *"Eric Wolford is a fine coach. We do not yet have the personnel he needs. The portal moves we made were better than no moves and worse than the moves we needed."*

The 11-2 final record was — and this is the line that matters — *the best regular season any non-defending-champion program had outside of the Big Ten that year*. By the standard the rest of the sport plays to, it was a triumph. Auburn fans would have built statues. Tennessee fans would have built statues twice. Even Florida fans would have stopped talking about the AD. By the standard Bama plays to — the Standard, the thing Saban built and DeBoer is now custodian of — it was the program's worst regular season since 2010. That gap, between what was good for college football and what was good for Bama, is the thing we are going to track for the next three chapters at minimum. As we noted in [Chapter 1](#chapter-1), the Standard does not retire. The Standard had spent fifteen years insisting that two losses was a bad year. Two losses was now a bad year.

The CFP run was a complicated success. Bama had a first-round bye (No. 4 seed, on the strength of the SEC Championship Game appearance and a regular-season profile that included a dominant win at Georgia in late September). The quarterfinal against Notre Dame, played in New Orleans on January 1, was the closest game of the bracket. ND won 27-24 on a controversial fourth-quarter spot that Joseph Goodman, in his AL.com postgame column, refused to litigate (*"the spot is the spot. Bama did not lose because of the spot. Bama lost because the offense could not generate a third-quarter touchdown that the offense should have generated. The spot was a moment. The third quarter was a structural problem"*). The game was Bama's most-watched non-Iron-Bowl game of the season. The game was also the moment a portion of the fanbase — the portion that had been waiting all year for the structural work to manifest — began to admit that the structural work was incomplete.

The Cole Cubelic post-Sugar Bowl morning show captured the tonal range. Cubelic, who had been the most-thoughtful caller-and-host on the transition all year, opened with: *"DeBoer's first year was a winning year. It was not a Bama year. The two are different things. The work to make those two things the same is the work of his second and third years. The fanbase that wants both at once will be unhappy. The fanbase that understands what the transition actually requires will be patient. I think most of you are in the second category. I think the talk-show callers will be in the first."* The line read accurately. The talk-show callers were in the first.

What had worked, in the verdict-time evaluation Aaron Suttles published in the Tuscaloosa News on January 5, was the offensive identity DeBoer had built. *"Bama's offense in 2024 was different from Bama's offense in 2023 in ways that are visible to anyone watching,"* Suttles wrote. *"More tempo. More motion. More 12 personnel. More designed quarterback runs in the red zone. The identity is recognizable as DeBoer's identity. It worked. It produced 36.4 points per game against the toughest schedule in college football. The complaints about the offense are not actually about the offense. They are about the moments the offense did not perform — Vanderbilt, second half against Tennessee, third quarter against Notre Dame. Those are real complaints. They are not complaints about the system. They are complaints about the personnel."*

The portal moves of the spring window — and we will track this through next year, when Chapter 4 lands — will be the moves the second cycle is judged on. As we noted in [Chapter 2](#chapter-2), DeBoer's portal philosophy is not Saban's. He took 15 in the spring of 2024. He is reportedly going to take 12 to 14 in the spring of 2025, with OL and DL specifically targeted. The recruiting class for 2025 is currently rated No. 4 nationally per most services — slightly below the Bama floor of the Saban era but not catastrophically. *"DeBoer is recruiting like a really good non-Bama coach,"* one TideFans poster wrote. *"He needs to recruit like Bama. The class will probably finish in the top five. The class needs to finish in the top three for Bama to be Bama. The first cycle of his classes is the one we are watching."*

This thread continues. The second cycle is going to be the one that produces the more-determinate verdict. We pick this up in Chapter 4 in the spring of '26.""",
        "byline": "From The Saban-to-DeBoer Transition Department",
        "published_at": "2025-01-08 11:00:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Joseph Goodman", "label": "AL.com Sugar Bowl postgame", "url": None, "date": "2025-01-02"},
            {"kind": "beat-writer", "name": "Aaron Suttles", "label": "Tuscaloosa News season verdict", "url": None, "date": "2025-01-05"},
            {"kind": "tv-radio", "name": "Cole Cubelic", "label": "WJOX morning show post-Sugar", "url": None, "date": "2025-01-03"},
            {"kind": "board", "name": "TideRollerSC", "label": "TideFans Vandy autopsy", "url": None, "date": "2024-10-06"},
        ],
        "pull_quote": "DeBoer's first year was a winning year. It was not a Bama year. The two are different things.",
    },
    {
        "chapter_number": 4,
        "title": "Spring 2026: The Standard, Re-Articulated",
        "dek": "Two cycles in. DeBoer's identity is showing. The OL has been rebuilt. The third recruiting class has landed. The Standard is being re-articulated in DeBoer's voice. The question is no longer whether it holds. The question is what it sounds like now.",
        "body_markdown": """The spring of 2026 finds Bama in the position the spring of 2025 was supposed to find Bama in: with a clear identity, a settled coaching staff, and a recruiting board that is competing for the same players Saban-era Bama would have competed for. The 2025 season — DeBoer's second — finished 12-1, with a regular-season loss at Tennessee that was the kind of road-environment loss the Saban-era program also occasionally absorbed, and a CFP semifinal exit to Ohio State that, by the verdict that landed in the boards' Sunday morning postgame threads, was the kind of loss the program could live with because the program had played the game on its own terms. *"We lost,"* TideRollerSC wrote on the morning of December 28. *"We lost the way Bama loses. That has not always been true the past two years. It is true today. That matters."*

We picked this thread up in [Chapter 1](#chapter-1) by asking whether the institution would survive the change in pulpit voice. We picked it up in [Chapter 2](#chapter-2) by tracking the texture of DeBoer's first camp. We picked it up in [Chapter 3](#chapter-3) by reckoning with the Vandy loss and the 11-2 first-year verdict. The two-cycle verdict is now a different shape: the Standard holds, but the Standard's *articulation* — the words, the rhythms, the day-to-day cadence, the press-conference vocabulary — is now DeBoer's. That is the change Saban-era Bama spent two decades resisting in its own continuity. The continuity is now broken. The continuity is also, surprisingly, intact in the ways that matter.

The clearest evidence of the re-articulation is the recruiting class for 2026. DeBoer's third class signed at No. 2 nationally per all major services, with eleven five-stars and the highest average per-player rating of any class Bama has signed since 2017. The class includes the No. 1 overall recruit (a defensive end from Memphis whose recruitment Saban had been managing personally before retiring), the No. 4 overall recruit (a quarterback from Houston who decommitted from Texas in November and committed to Bama in early February), and a four-star OL haul of seven players — the largest single-class OL infusion in program history. *"The OL question is no longer the OL question,"* Aaron Suttles wrote in the Tuscaloosa News on February 5, the morning after signing day. *"The OL question is now what kind of line the staff develops out of the talent it has stockpiled. That is a coaching question. That is a winnable question."*

The portal complement to the recruiting class has been smaller than DeBoer's first-year hauls. He took eight players in the spring 2026 window, with three at OL and one at quarterback (a backup move, not a starter move — Milroe had departed for the NFL after his junior year, and Ty Simpson had won the QB1 job decisively in the fall). The smaller portal number is the data point that signals the second-order shift the Bama people have been waiting for. *"DeBoer no longer needs to portal his way into competence,"* Joseph Goodman wrote in his AL.com column on February 8. *"He can recruit at the level Bama recruits. The portal is now a tool he uses sparingly, the way Saban eventually used it sparingly. The transition is not yet complete. It is meaningfully more advanced than it was two years ago. We are now looking at a Bama that is recognizably Bama in its roster construction, with a head coach whose play-calling identity is no longer being measured against the predecessor's because the predecessor's identity has been retired."*

The boards have arrived at a settled view that they did not have a year ago. The TideFans thread CrimsonAndCool opened in mid-March titled *"Year three: where we are"* ran 480 replies and the dominant tone was confident in a way the boards had not allowed themselves to be in 2024. *"DeBoer is the head coach,"* one reply read. *"He is not Saban. He is not pretending to be Saban. He is also not failing to be Bama. The two distinctions are the work of his first three years. The work is done. The next chapter is not whether he can be Bama. The next chapter is what kind of Bama he is going to build. Roll Tide."* The Roll Tide at the end was — and we mean this in the institutional-affection sense — the first time in two years a TideFans thread of that length had ended on the program's traditional sign-off without it reading as either defensive or wishful. It read as settled.

What DeBoer's Bama is going to look like in the back half of his contract — and the contract, extended in October 2025, runs through 2030 — is the thing we are going to track from here. The early indicators: a slightly more open offense than Saban's late-career teams ran, a more aggressive defense than Saban's late-career teams ran, a portal philosophy that uses the portal as a precision tool rather than a roster-building strategy, and a recruiting board that competes for everyone Saban-era Bama competed for. The institutional weight that we wrote about in [Chapter 1](#chapter-1) has not lessened. The institutional weight is now being borne by a coach who is not the man who built it, and the institution has spent two years figuring out what that means.

The Cole Cubelic line that we returned to in earlier chapters — *"Nick Saban built the church. Kalen DeBoer is the new pastor. The church doesn't change"* — has aged remarkably well. The church has not changed. The pastor's voice is now the voice the congregation hears on Sundays, and the congregation has, in the spring of 2026, mostly stopped comparing the new voice to the old one. That is the deepest thing the transition was ever going to require. The transition has, broadly, accomplished it.

We pick this up in chapter five whenever the next meaningful inflection lands. Probably the back half of the 2026 season. Probably whatever DeBoer's first marquee playoff run looks like.""",
        "byline": "From The Saban-to-DeBoer Transition Department",
        "published_at": "2026-04-21 10:30:00",
        "read_time_minutes": 8,
        "referenced_chapter_ids": [1, 2, 3],
        "referenced_sources": [
            {"kind": "beat-writer", "name": "Aaron Suttles", "label": "Tuscaloosa News signing day analysis", "url": None, "date": "2026-02-05"},
            {"kind": "beat-writer", "name": "Joseph Goodman", "label": "AL.com column", "url": None, "date": "2026-02-08"},
            {"kind": "board", "name": "TideRollerSC", "label": "TideFans CFP semi postgame", "url": None, "date": "2025-12-28"},
            {"kind": "board", "name": "CrimsonAndCool", "label": "TideFans 'Year three' thread", "url": None, "date": "2026-03-12"},
        ],
        "pull_quote": "DeBoer is the head coach. He is not Saban. He is not pretending to be Saban. He is also not failing to be Bama.",
    },
]
