# setup_langfuse_local.ps1
# Brings up a self-hosted Langfuse stack via Docker Compose.
# Canonical configuration based on Langfuse v3 docker-compose as of May 2026.
# https://langfuse.com/docs/deployment/self-host

param(
    [string]$ComposeFile = "docker-compose.langfuse.yml",
    [string]$LangfusePort = "3000",
    [string]$ClickhousePort = "8123",
    [string]$PostgresPort = "5432"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== Chronicle / Langfuse Local Setup ===" -ForegroundColor Cyan
Write-Host ""

# ---------------------------------------------------------------------------
# 1. Check Docker is running
# ---------------------------------------------------------------------------

Write-Host "[1/5] Checking Docker..." -ForegroundColor Yellow
try {
    $dockerInfo = docker info 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Docker daemon is not running. Start Docker Desktop and retry." -ForegroundColor Red
        exit 1
    }
    Write-Host "      Docker is running." -ForegroundColor Green
} catch {
    Write-Host "ERROR: docker command not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/" -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# 2. Generate secrets (idempotent — skip if already set in .env)
# ---------------------------------------------------------------------------

Write-Host "[2/5] Generating secrets..." -ForegroundColor Yellow

$EnvFile = ".env"
$SecretsGenerated = $false

# Load existing .env if present
$ExistingEnv = @{}
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match "^([^#][^=]*)=(.*)$") {
            $ExistingEnv[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }
}

function New-RandomSecret {
    param([int]$Length = 32)
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    -join (1..$Length | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
}

$NextAuthSecret      = if ($ExistingEnv["NEXTAUTH_SECRET"])       { $ExistingEnv["NEXTAUTH_SECRET"] }       else { New-RandomSecret 32; $SecretsGenerated = $true }
$SaltSecret          = if ($ExistingEnv["SALT"])                   { $ExistingEnv["SALT"] }                   else { New-RandomSecret 32; $SecretsGenerated = $true }
$ClickhousePassword  = if ($ExistingEnv["CLICKHOUSE_PASSWORD"])    { $ExistingEnv["CLICKHOUSE_PASSWORD"] }    else { New-RandomSecret 24; $SecretsGenerated = $true }
$PostgresPassword    = if ($ExistingEnv["LANGFUSE_POSTGRES_PASS"]) { $ExistingEnv["LANGFUSE_POSTGRES_PASS"] } else { New-RandomSecret 24; $SecretsGenerated = $true }

# Re-derive these in case they were previously set with wrong values
$DatabaseUrl = "postgresql://langfuse:${PostgresPassword}@langfuse-postgres:5432/langfuse"

if ($SecretsGenerated) {
    Write-Host "      New secrets generated." -ForegroundColor Green
} else {
    Write-Host "      Reusing existing secrets from $EnvFile." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 3. Write docker-compose.langfuse.yml if not present
# ---------------------------------------------------------------------------

Write-Host "[3/5] Writing $ComposeFile..." -ForegroundColor Yellow

if (Test-Path $ComposeFile) {
    Write-Host "      $ComposeFile already exists — skipping (delete to regenerate)." -ForegroundColor Green
} else {

$ComposeContent = @"
# Langfuse v3 self-hosted stack — generated by setup_langfuse_local.ps1
# Canonical reference: https://langfuse.com/docs/deployment/self-host
# Components: Langfuse web + worker, Postgres, ClickHouse, Redis

version: "3.9"

services:
  # ── Postgres ────────────────────────────────────────────────────────────
  langfuse-postgres:
    image: postgres:16-alpine
    container_name: langfuse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: "${PostgresPassword}"
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
    ports:
      - "${PostgresPort}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── ClickHouse ──────────────────────────────────────────────────────────
  langfuse-clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: langfuse-clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: langfuse
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_PASSWORD: "${ClickhousePassword}"
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
    ports:
      - "${ClickhousePort}:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "langfuse",
             "--password", "${ClickhousePassword}", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis ────────────────────────────────────────────────────────────────
  langfuse-redis:
    image: redis:7-alpine
    container_name: langfuse-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - langfuse_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Langfuse Web ─────────────────────────────────────────────────────────
  langfuse-web:
    image: ghcr.io/langfuse/langfuse:3
    container_name: langfuse-web
    restart: unless-stopped
    depends_on:
      langfuse-postgres:
        condition: service_healthy
      langfuse-clickhouse:
        condition: service_healthy
      langfuse-redis:
        condition: service_healthy
    ports:
      - "${LangfusePort}:3000"
    environment:
      DATABASE_URL: "postgresql://langfuse:${PostgresPassword}@langfuse-postgres:5432/langfuse"
      NEXTAUTH_URL: "http://localhost:${LangfusePort}"
      NEXTAUTH_SECRET: "${NextAuthSecret}"
      SALT: "${SaltSecret}"
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
      # ClickHouse
      CLICKHOUSE_URL: "http://langfuse-clickhouse:8123"
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_PASSWORD: "${ClickhousePassword}"
      # Redis
      REDIS_HOST: langfuse-redis
      REDIS_PORT: "6379"
      # Seed initial admin user (remove after first login)
      LANGFUSE_INIT_ORG_ID: chronicle
      LANGFUSE_INIT_ORG_NAME: "CFB Chronicle"
      LANGFUSE_INIT_PROJECT_ID: cfb-chronicle
      LANGFUSE_INIT_PROJECT_NAME: "CFB Chronicle Cards"
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "pk-lf-cfb-chronicle-dev"
      LANGFUSE_INIT_PROJECT_SECRET_KEY: "sk-lf-cfb-chronicle-dev"
      LANGFUSE_INIT_USER_EMAIL: "admin@localhost"
      LANGFUSE_INIT_USER_NAME: "admin"
      LANGFUSE_INIT_USER_PASSWORD: "changeme123"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/api/public/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  # ── Langfuse Worker ──────────────────────────────────────────────────────
  langfuse-worker:
    image: ghcr.io/langfuse/langfuse-worker:3
    container_name: langfuse-worker
    restart: unless-stopped
    depends_on:
      langfuse-web:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://langfuse:${PostgresPassword}@langfuse-postgres:5432/langfuse"
      CLICKHOUSE_URL: "http://langfuse-clickhouse:8123"
      CLICKHOUSE_USER: langfuse
      CLICKHOUSE_PASSWORD: "${ClickhousePassword}"
      REDIS_HOST: langfuse-redis
      REDIS_PORT: "6379"
      SALT: "${SaltSecret}"

volumes:
  langfuse_postgres_data:
  langfuse_clickhouse_data:
  langfuse_redis_data:
"@

    Set-Content -Path $ComposeFile -Value $ComposeContent -Encoding UTF8
    Write-Host "      Written $ComposeFile." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 4. Update .env with Langfuse connection vars
# ---------------------------------------------------------------------------

Write-Host "[4/5] Updating $EnvFile with Langfuse connection vars..." -ForegroundColor Yellow

$EnvAdditions = @"

# ── Langfuse (generated by setup_langfuse_local.ps1) ─────────────────────
LANGFUSE_HOST=http://localhost:${LangfusePort}
LANGFUSE_PUBLIC_KEY=pk-lf-cfb-chronicle-dev
LANGFUSE_SECRET_KEY=sk-lf-cfb-chronicle-dev
CHRONICLE_OBS_ENABLED=1

# Internal secrets (do not share)
NEXTAUTH_SECRET=${NextAuthSecret}
SALT=${SaltSecret}
LANGFUSE_POSTGRES_PASS=${PostgresPassword}
CLICKHOUSE_PASSWORD=${ClickhousePassword}
"@

# Append only if LANGFUSE_HOST not already set
if (-not $ExistingEnv.ContainsKey("LANGFUSE_HOST")) {
    Add-Content -Path $EnvFile -Value $EnvAdditions -Encoding UTF8
    Write-Host "      Added Langfuse vars to $EnvFile." -ForegroundColor Green
} else {
    Write-Host "      $EnvFile already has LANGFUSE_HOST — skipping append." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 5. Start the stack
# ---------------------------------------------------------------------------

Write-Host "[5/5] Starting Langfuse stack (docker compose up -d)..." -ForegroundColor Yellow

try {
    docker compose -f $ComposeFile up -d
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: docker compose up failed. Check Docker logs." -ForegroundColor Red
        exit 1
    }
} catch {
    # Fallback for older Docker installs that use docker-compose (v1 CLI)
    Write-Host "      docker compose failed — retrying with docker-compose..." -ForegroundColor Yellow
    docker-compose -f $ComposeFile up -d
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "=== Langfuse stack is starting ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Dashboard URL : http://localhost:${LangfusePort}" -ForegroundColor White
Write-Host "  Login email   : admin@localhost" -ForegroundColor White
Write-Host "  Login password: changeme123  (change this after first login)" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Public key    : pk-lf-cfb-chronicle-dev" -ForegroundColor White
Write-Host "  Secret key    : sk-lf-cfb-chronicle-dev" -ForegroundColor White
Write-Host ""
Write-Host "  Env vars written to $EnvFile — load with:" -ForegroundColor White
Write-Host "    `$env:LANGFUSE_HOST='http://localhost:${LangfusePort}'" -ForegroundColor DarkGray
Write-Host "    `$env:LANGFUSE_PUBLIC_KEY='pk-lf-cfb-chronicle-dev'" -ForegroundColor DarkGray
Write-Host "    `$env:LANGFUSE_SECRET_KEY='sk-lf-cfb-chronicle-dev'" -ForegroundColor DarkGray
Write-Host "    `$env:CHRONICLE_OBS_ENABLED='1'" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  The web container takes ~30 s to be fully ready." -ForegroundColor Yellow
Write-Host "  Watch progress: docker compose -f $ComposeFile logs -f langfuse-web" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  To tear down:  docker compose -f $ComposeFile down" -ForegroundColor DarkGray
Write-Host "  To purge data: docker compose -f $ComposeFile down -v" -ForegroundColor DarkGray
Write-Host ""
