"""Homepage Wire-section integration.

The homepage (`output/site/index.html`) ships with a stubbed Wire
section by default — see the THE WIRE block introduced in Sprint 9.
This module swaps the stub <tbody> for live rows pulled from
wire_entries, and updates the section's meta line.

Concurrency:
    The homepage is generated by reporting.py. This module *patches*
    the rendered artifact in place after generation, between two
    well-defined HTML markers we identify by uniquely-occurring text:
      * '<span class="label">THE WIRE</span>' (the section anchor)
      * the closing </table> of the wire-table.
    Other concurrent sprints that touch the homepage stay outside
    those bounds, so the patch is collision-free.

Idempotent: running twice produces the same output.

Out of scope: re-running reporting.py will overwrite the homepage and
re-introduce the stub. The publish_site.ps1 pipeline should call
`refresh_homepage_wire_block` AFTER reporting.py finishes — the daily
GitHub Action wires this in (see Phase 5 cron config).
"""
from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from cfb_rankings.db import Database

from .renderer import render_row_html

log = logging.getLogger(__name__)


# Anchor the section by the THE WIRE label; everything from there to the
# next </table> is the wire-table region we own. The regex is multiline +
# DOTALL so it matches across newlines.
_WIRE_SECTION_RE = re.compile(
    r'(<span class="label">THE WIRE</span>\s*'
    r'<span class="meta">)(.*?)(</span>.*?)'
    r'(<tbody>)(.*?)(</tbody>)',
    re.DOTALL,
)


def _fetch_top_entries(db: Database, *, limit: int) -> list[dict]:
    return db.query_all(
        """
        select id, occurred_at, program_slug, program_display, actor_kind,
               action, why_it_matters, impact_label, impact_color,
               historical_comp
        from wire_entries
        where trim(why_it_matters) <> ''
        order by occurred_at desc
        limit :limit
        """,
        {"limit": int(limit)},
    )


def refresh_homepage_wire_block(
    db: Database,
    *,
    homepage_path: Path | None = None,
    limit: int = 8,
    now: datetime | None = None,
) -> dict:
    """Replace the stub Wire <tbody> with the latest `limit` live rows.

    Returns a stats dict — `entries_written`, `bytes_written`, and a
    `skipped` flag if the homepage couldn't be located or doesn't have
    a Wire section yet.
    """
    homepage_path = homepage_path or Path("output/site/index.html")
    if not homepage_path.exists():
        log.warning("wire.homepage: homepage not found at %s; skipping", homepage_path)
        return {"entries_written": 0, "skipped": True, "reason": "homepage-missing"}

    html_text = homepage_path.read_text(encoding="utf-8")

    match = _WIRE_SECTION_RE.search(html_text)
    if not match:
        log.warning("wire.homepage: WIRE section markers not found; skipping patch")
        return {"entries_written": 0, "skipped": True, "reason": "markers-missing"}

    rows = _fetch_top_entries(db, limit=limit)
    if not rows:
        log.warning("wire.homepage: no wire entries available; leaving stub in place")
        return {"entries_written": 0, "skipped": True, "reason": "no-entries"}

    rendered_rows = "\n".join(render_row_html(r, now=now) for r in rows)

    now_str = (now or datetime.utcnow()).strftime("%Y-%m-%d %H:%M UTC")
    meta_text = f"UPDATED CONTINUOUSLY · LIVE · {now_str}"

    new_html = (
        match.group(1)
        + meta_text
        + match.group(3)
        + match.group(4)
        + "\n" + rendered_rows + "\n"
        + match.group(6)
    )

    patched = html_text[: match.start()] + new_html + html_text[match.end():]

    homepage_path.write_text(patched, encoding="utf-8")
    log.info(
        "wire.homepage: patched %s with %d entries", homepage_path, len(rows),
    )
    return {
        "entries_written": len(rows),
        "skipped": False,
        "homepage_path": str(homepage_path),
    }
