"""Offseason fallback Wire entries for display when database is empty.

This module provides sample Wire entries that can be used during the
offseason when the database has no recruiting or portal data. These are
designed to look realistic and give users a sense of what the Wire will
show when the season is active.
"""

from datetime import datetime, timedelta
from typing import Any, List


# Sample offseason Wire entries - designed to look realistic
# These represent typical offseason transactions
OFFSEASON_FALLBACK_ENTRIES = [
    {
        "occurred_at": datetime.utcnow() - timedelta(days=2),
        "program_slug": "ohio-state",
        "program_display": "Ohio State",
        "action": "Five-star QB Quinn Ewers enters transfer portal",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 85,
        "related_thread_slug": None,
        "why_it_matters": "Quarterback carousel continues. Ewers was the centerpiece of Texas' offense, and his departure leaves a massive hole in Austin. For Ohio State, this is a potential program-defining addition.",
        "impact_label": "BLOCKBUSTER",
        "impact_color": "amber",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=3),
        "program_slug": "alabama",
        "program_display": "Alabama",
        "action": "Five-star WR Ryan Williams commits 2026",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 80,
        "related_thread_slug": None,
        "why_it_matters": "Williams was Alabama's top target in the 2026 class and showed flashes of elite play as a true freshman. His commitment gives the Tide another explosive weapon for their offense.",
        "impact_label": "BLUE CHIP",
        "impact_color": "green",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=4),
        "program_slug": "georgia",
        "program_display": "Georgia",
        "action": "DC Glenn Schumann leaves for NFL head coaching opportunity",
        "actor_kind": "coach",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 75,
        "related_thread_slug": None,
        "why_it_matters": "Schumann was the architect of Georgia's dominant defense. His departure leaves a significant void in Athens and could impact recruiting momentum.",
        "impact_label": "COACHING MOVE",
        "impact_color": "amber",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=5),
        "program_slug": "texas",
        "program_display": "Texas",
        "action": "Five-star CB Derek Williams commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 70,
        "related_thread_slug": None,
        "why_it_matters": "Williams is the top cornerback in the 2027 class and gives Texas a lockdown defender for years to come. This is a major recruiting win for the Longhorns.",
        "impact_label": "BLUE CHIP",
        "impact_color": "green",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=6),
        "program_slug": "oregon",
        "program_display": "Oregon",
        "action": "Five-star EDGE Matayo Uiagalelei enters transfer portal",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 82,
        "related_thread_slug": None,
        "why_it_matters": "Uiagalelei was a breakout star for Oregon and his departure is a significant loss. His combination of size and speed will make him the most sought-after EDGE on the market.",
        "impact_label": "PORTAL MOVE",
        "impact_color": "amber",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=7),
        "program_slug": "miami-fla",
        "program_display": "Miami",
        "action": "Four-star QB Jaden Davis flips from Florida State",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 72,
        "related_thread_slug": None,
        "why_it_matters": "Davis is a pro-style quarterback with NFL pedigree. His flip from FSU to Miami is a significant recruiting victory and strengthens Miami's quarterback depth.",
        "impact_label": "FLIP",
        "impact_color": "muted",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=8),
        "program_slug": "clemson",
        "program_display": "Clemson",
        "action": "Five-star WR Bryant Wesco Jr. commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 75,
        "related_thread_slug": None,
        "why_it_matters": "Wesco is arguably the top receiver in the 2027 class. His commitment gives Clemson another weapon and continues their dominance in recruiting elite pass-catchers.",
        "impact_label": "BLUE CHIP",
        "impact_color": "green",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=9),
        "program_slug": "notre-dame",
        "program_display": "Notre Dame",
        "action": "Four-star RB Kedren Young commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 68,
        "related_thread_slug": None,
        "why_it_matters": "Young is a physical running back with breakaway speed. His commitment bolsters Notre Dame's backfield and adds another weapon to their offensive arsenal.",
        "impact_label": "COMMIT",
        "impact_color": "muted",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=10),
        "program_slug": "oklahoma",
        "program_display": "Oklahoma",
        "action": "Five-star QB Kevin Sperry flips from Texas A&M",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 78,
        "related_thread_slug": None,
        "why_it_matters": "Sperry is an elite quarterback prospect with a big arm. His flip from A&M to Oklahoma is a significant recruiting win and could shape the Big 12 championship race for years.",
        "impact_label": "FLIP",
        "impact_color": "amber",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=12),
        "program_slug": "lsu",
        "program_display": "LSU",
        "action": "Five-star SDE Dominick McKinley commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 73,
        "related_thread_slug": None,
        "why_it_matters": "McKinley is a disruptive pass rusher with elite burst. His commitment gives LSU a foundational piece for their defensive line and continues their recruiting momentum.",
        "impact_label": "COMMIT",
        "impact_color": "muted",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=14),
        "program_slug": "usc",
        "program_display": "USC",
        "action": "Five-star ATH Jahzeer Joseph commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 76,
        "related_thread_slug": None,
        "why_it_matters": "Joseph is an elite athlete with positional versatility. His commitment to USC is a major recruiting win and gives Lincoln Riley another dynamic playmaker to work with.",
        "impact_label": "BLUE CHIP",
        "impact_color": "green",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=16),
        "program_slug": "michigan",
        "program_display": "Michigan",
        "action": "Four-star EDGE Dominic Zappa enters transfer portal",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 70,
        "related_thread_slug": None,
        "why_it_matters": "Zappa was a key contributor to Michigan's championship run and his departure creates uncertainty in their pass rush rotation. Multiple programs will be interested in his services.",
        "impact_label": "PORTAL MOVE",
        "impact_color": "amber",
    },
    {
        "occurred_at": datetime.utcnow() - timedelta(days=18),
        "program_slug": "penn-state",
        "program_display": "Penn State",
        "action": "Five-star OT Andrew Babcock commits 2027",
        "actor_kind": "player",
        "source_kind": "unverified",
        "source_url": None,
        "source_name": "Sample offseason data",
        "fan_intel_velocity_spike": 71,
        "related_thread_slug": None,
        "why_it_matters": "Babcock is an elite offensive tackle prospect with excellent footwork. His commitment strengthens Penn State's offensive line and addresses a critical position of need.",
        "impact_label": "BLUE CHIP",
        "impact_color": "green",
    },
]


def get_offseason_fallback_entries() -> List[dict[str, Any]]:
    """Return sample Wire entries for offseason display.

    These entries are used when the database has no real recruiting or
    portal data. They are designed to look realistic and give users a
    sense of what the Wire will show when the season is active.

    Returns:
        List of Wire entry dictionaries with all required fields.
    """
    return OFFSEASON_FALLBACK_ENTRIES
